import { Product } from '../../types/product';

export const coffeeProducts: Product[] = [
  {
    id: 'prod-coffee-1',
    handle: 'ethiopian-yirgacheffe-single-origin',
    title: 'Ethiopian Yirgacheffe Single Origin',
    subtitle: 'Washed heirloom varietal with jasmine floral and bergamot notes',
    description: 'Harvested from the Gedeo zone at elevations above 2,000 meters, this exceptional washed micro-lot showcases quintessential Yirgacheffe brilliance. Crisp acidity balanced by sweet mandarin orange, jasmine florals, and a delicate honey finish.',
    price: 22.0,
    compareAtPrice: 26.0,
    category: 'Single Origin',
    tags: ['single-origin', 'light-roast', 'washed', 'ethiopia', 'floral', 'bestseller'],
    images: [
      {
        id: 'img-coffee-1-1',
        url: 'https://images.unsplash.com/photo-1587734195503-904fca47e0e9?auto=format&fit=crop&w=800&q=80',
        altText: 'Bag of Ethiopian Yirgacheffe single origin coffee beans with whole roasted beans scattered',
      },
      {
        id: 'img-coffee-1-2',
        url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80',
        altText: 'Pour over brew showing light amber clarity of Ethiopian Yirgacheffe roast',
      },
    ],
    options: [
      { name: 'Grind', values: ['Whole Bean', 'Filter Grind', 'Espresso Grind', 'French Press'] },
      { name: 'Weight', values: ['250g', '500g', '1kg'] },
    ],
    variants: [
      {
        id: 'var-coffee-1-1',
        title: 'Whole Bean / 250g',
        sku: 'COF-ETH-WB-250',
        price: 22.0,
        compareAtPrice: 26.0,
        options: { Grind: 'Whole Bean', Weight: '250g' },
        availableForSale: true,
        inventoryQuantity: 34,
        imageUrl: 'https://images.unsplash.com/photo-1587734195503-904fca47e0e9?auto=format&fit=crop&w=800&q=80',
      },
      {
        id: 'var-coffee-1-2',
        title: 'Whole Bean / 500g',
        sku: 'COF-ETH-WB-500',
        price: 38.0,
        compareAtPrice: 44.0,
        options: { Grind: 'Whole Bean', Weight: '500g' },
        availableForSale: true,
        inventoryQuantity: 22,
        imageUrl: 'https://images.unsplash.com/photo-1587734195503-904fca47e0e9?auto=format&fit=crop&w=800&q=80',
      },
      {
        id: 'var-coffee-1-3',
        title: 'Filter Grind / 250g',
        sku: 'COF-ETH-FG-250',
        price: 22.0,
        options: { Grind: 'Filter Grind', Weight: '250g' },
        availableForSale: true,
        inventoryQuantity: 18,
        imageUrl: 'https://images.unsplash.com/photo-1587734195503-904fca47e0e9?auto=format&fit=crop&w=800&q=80',
      },
      {
        id: 'var-coffee-1-4',
        title: 'Espresso Grind / 250g',
        sku: 'COF-ETH-EG-250',
        price: 22.0,
        options: { Grind: 'Espresso Grind', Weight: '250g' },
        availableForSale: true,
        inventoryQuantity: 12,
        imageUrl: 'https://images.unsplash.com/photo-1587734195503-904fca47e0e9?auto=format&fit=crop&w=800&q=80',
      },
    ],
    rating: { average: 4.9, count: 68 },
    specifications: {
      Origin: 'Gedeo Zone, Yirgacheffe, Ethiopia',
      Altitude: '2,050m - 2,200m',
      Process: 'Washed, Sun Dried on Raised Beds',
      RoastLevel: 'Light-Medium',
      FlavorNotes: 'Jasmine Floral, Bergamot, Mandarin, Wild Honey',
    },
    featured: true,
    createdAt: '2026-01-10T08:00:00Z',
  },
  {
    id: 'prod-coffee-2',
    handle: 'guatemala-antigua-volcanic-reserve',
    title: 'Guatemala Antigua Volcanic Reserve',
    subtitle: 'Shade-grown Bourbon and Caturra from mineral-rich volcanic terroir',
    description: 'Surrounded by three volcanoes in the celebrated Antigua valley, these shade-grown beans develop rich density. Boasts a velvety body with profound cocoa nibs, spiced apple cider brightness, and a long hazelnut praline finish.',
    price: 20.0,
    category: 'Single Origin',
    tags: ['single-origin', 'medium-roast', 'guatemala', 'chocolate', 'volcanic'],
    images: [
      {
        id: 'img-coffee-2-1',
        url: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?auto=format&fit=crop&w=800&q=80',
        altText: 'Whole roasted Guatemala Antigua coffee beans in scoop',
      },
      {
        id: 'img-coffee-2-2',
        url: 'https://images.unsplash.com/photo-1509785307050-d4066910ec1e?auto=format&fit=crop&w=800&q=80',
        altText: 'Ceramic mug of freshly extracted Antigua roast with rich hazelnut crema',
      },
    ],
    options: [
      { name: 'Grind', values: ['Whole Bean', 'Filter Grind', 'French Press'] },
      { name: 'Weight', values: ['250g', '500g', '1kg'] },
    ],
    variants: [
      {
        id: 'var-coffee-2-1',
        title: 'Whole Bean / 250g',
        sku: 'COF-GUA-WB-250',
        price: 20.0,
        options: { Grind: 'Whole Bean', Weight: '250g' },
        availableForSale: true,
        inventoryQuantity: 42,
        imageUrl: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?auto=format&fit=crop&w=800&q=80',
      },
      {
        id: 'var-coffee-2-2',
        title: 'Filter Grind / 250g',
        sku: 'COF-GUA-FG-250',
        price: 20.0,
        options: { Grind: 'Filter Grind', Weight: '250g' },
        availableForSale: true,
        inventoryQuantity: 25,
        imageUrl: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?auto=format&fit=crop&w=800&q=80',
      },
      {
        id: 'var-coffee-2-3',
        title: 'Whole Bean / 500g',
        sku: 'COF-GUA-WB-500',
        price: 36.0,
        options: { Grind: 'Whole Bean', Weight: '500g' },
        availableForSale: true,
        inventoryQuantity: 19,
        imageUrl: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?auto=format&fit=crop&w=800&q=80',
      },
    ],
    rating: { average: 4.8, count: 52 },
    specifications: {
      Origin: 'Antigua Valley, Sacatepéquez, Guatemala',
      Altitude: '1,650m - 1,850m',
      Process: 'Fully Washed',
      RoastLevel: 'Medium',
      FlavorNotes: 'Dark Chocolate, Candied Orange, Nutmeg, Hazelnut',
    },
    featured: true,
    createdAt: '2026-01-12T08:00:00Z',
  },
  {
    id: 'prod-coffee-3',
    handle: 'colombian-supremo-reserve',
    title: 'Colombian Supremo Reserve',
    subtitle: 'High-elevation Huila micro-lot with brown sugar and red apple notes',
    description: 'Hand-selected by second-generation growers in San Agustín, Huila. Supremo-grade beans are graded by bean screen size 17/18, delivering exceptional cup sweetness with silky caramel, red currant, and toasted pecan tones.',
    price: 19.5,
    compareAtPrice: 23.0,
    category: 'Single Origin',
    tags: ['single-origin', 'medium-roast', 'colombia', 'caramel', 'classic'],
    images: [
      {
        id: 'img-coffee-3-1',
        url: 'https://images.unsplash.com/photo-1611854779393-1b2da9d400fe?auto=format&fit=crop&w=800&q=80',
        altText: 'Raw green and roasted Colombian Supremo beans displayed side-by-side',
      },
    ],
    options: [
      { name: 'Grind', values: ['Whole Bean', 'Filter Grind', 'Espresso Grind'] },
      { name: 'Weight', values: ['250g', '500g'] },
    ],
    variants: [
      {
        id: 'var-coffee-3-1',
        title: 'Whole Bean / 250g',
        sku: 'COF-COL-WB-250',
        price: 19.5,
        compareAtPrice: 23.0,
        options: { Grind: 'Whole Bean', Weight: '250g' },
        availableForSale: true,
        inventoryQuantity: 50,
      },
      {
        id: 'var-coffee-3-2',
        title: 'Espresso Grind / 250g',
        sku: 'COF-COL-EG-250',
        price: 19.5,
        compareAtPrice: 23.0,
        options: { Grind: 'Espresso Grind', Weight: '250g' },
        availableForSale: true,
        inventoryQuantity: 30,
      },
    ],
    rating: { average: 4.7, count: 47 },
    specifications: {
      Origin: 'San Agustín, Huila, Colombia',
      Altitude: '1,750m',
      Process: 'Washed, Patio Dried',
      RoastLevel: 'Medium',
      FlavorNotes: 'Caramel Panela, Red Apple, Toasted Pecan',
    },
    featured: true,
    createdAt: '2026-01-14T08:00:00Z',
  },
  {
    id: 'prod-coffee-4',
    handle: 'sumatra-mandheling-dark-earth',
    title: 'Sumatra Mandheling Dark Earth',
    subtitle: 'Traditional Giling Basah wet-hulled profile with cedar and dark cocoa',
    description: 'Cultivated in the volcanic volcanic highlands surrounding Lake Toba. Wet-hulling creates low acidity with unmatched syrup-like body, dark baker chocolate depth, pipe tobacco aromatics, and forest floor complexity.',
    price: 21.0,
    category: 'Single Origin',
    tags: ['single-origin', 'dark-roast', 'sumatra', 'earthy', 'bold'],
    images: [
      {
        id: 'img-coffee-4-1',
        url: 'https://images.unsplash.com/photo-1511920170033-f8396924c348?auto=format&fit=crop&w=800&q=80',
        altText: 'Dark roasted glossy Sumatra Mandheling coffee beans in artisan jar',
      },
    ],
    options: [
      { name: 'Grind', values: ['Whole Bean', 'French Press'] },
      { name: 'Weight', values: ['250g', '500g'] },
    ],
    variants: [
      {
        id: 'var-coffee-4-1',
        title: 'Whole Bean / 250g',
        sku: 'COF-SUM-WB-250',
        price: 21.0,
        options: { Grind: 'Whole Bean', Weight: '250g' },
        availableForSale: true,
        inventoryQuantity: 28,
      },
      {
        id: 'var-coffee-4-2',
        title: 'French Press / 250g',
        sku: 'COF-SUM-FP-250',
        price: 21.0,
        options: { Grind: 'French Press', Weight: '250g' },
        availableForSale: true,
        inventoryQuantity: 15,
      },
    ],
    rating: { average: 4.8, count: 39 },
    specifications: {
      Origin: 'Lintong Nihuta, North Sumatra, Indonesia',
      Altitude: '1,400m - 1,550m',
      Process: 'Wet-Hulled (Giling Basah)',
      RoastLevel: 'Dark',
      FlavorNotes: 'Dark Baker Chocolate, Cedar, Sweet Tobacco, Clove',
    },
    featured: true,
    createdAt: '2026-01-16T08:00:00Z',
  },
  {
    id: 'prod-coffee-5',
    handle: 'kenyan-aa-highland-harvest',
    title: 'Kenyan AA Highland Harvest',
    subtitle: 'Phosphoric acidity with blackcurrant, ruby grapefruit, and cane sugar',
    description: 'Grown on the slopes of Mount Kenya, this pristine AA grade lot represents the pinnacle of East African coffees. Double-fermented and meticulously washed, yielding electrifying blackcurrant sweetness and wine-like complexity.',
    price: 24.5,
    compareAtPrice: 28.0,
    category: 'Single Origin',
    tags: ['single-origin', 'light-roast', 'kenya', 'citrus', 'blackcurrant'],
    images: [
      {
        id: 'img-coffee-5-1',
        url: 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=800&q=80',
        altText: 'Lush green coffee cherries on Mount Kenya highland branch',
      },
    ],
    options: [
      { name: 'Grind', values: ['Whole Bean', 'Filter Grind'] },
      { name: 'Weight', values: ['250g', '500g'] },
    ],
    variants: [
      {
        id: 'var-coffee-5-1',
        title: 'Whole Bean / 250g',
        sku: 'COF-KEN-WB-250',
        price: 24.5,
        compareAtPrice: 28.0,
        options: { Grind: 'Whole Bean', Weight: '250g' },
        availableForSale: true,
        inventoryQuantity: 20,
      },
    ],
    rating: { average: 4.9, count: 41 },
    specifications: {
      Origin: 'Nyeri County, Central Highlands, Kenya',
      Altitude: '1,900m',
      Process: 'Double Washed',
      RoastLevel: 'Light',
      FlavorNotes: 'Blackcurrant, Ruby Grapefruit, Cane Sugar, Black Tea',
    },
    featured: false,
    createdAt: '2026-01-18T08:00:00Z',
  },
  {
    id: 'prod-coffee-6',
    handle: 'costa-rica-tarrazu-honey-process',
    title: 'Costa Rica Tarrazu Honey Process',
    subtitle: 'Yellow honey processed Caturra with golden raisin and ripe plum',
    description: 'From the mountainous Tarrazú micro-climate. By leaving a portion of the mucilage intact during drying on raised African beds, the bean absorbs intense fruit sugars, creating a creamy mouthfeel and notes of apricot jam.',
    price: 21.5,
    category: 'Single Origin',
    tags: ['single-origin', 'medium-roast', 'costa-rica', 'honey-process', 'sweet'],
    images: [
      {
        id: 'img-coffee-6-1',
        url: 'https://images.unsplash.com/photo-1518832553480-cd0e625ed3e6?auto=format&fit=crop&w=800&q=80',
        altText: 'Honey process coffee parchment drying on raised wooden beds in Costa Rica',
      },
    ],
    options: [
      { name: 'Grind', values: ['Whole Bean', 'Filter Grind', 'Espresso Grind'] },
      { name: 'Weight', values: ['250g', '500g'] },
    ],
    variants: [
      {
        id: 'var-coffee-6-1',
        title: 'Whole Bean / 250g',
        sku: 'COF-CR-WB-250',
        price: 21.5,
        options: { Grind: 'Whole Bean', Weight: '250g' },
        availableForSale: true,
        inventoryQuantity: 33,
      },
    ],
    rating: { average: 4.8, count: 35 },
    specifications: {
      Origin: 'Tarrazú Valley, San José, Costa Rica',
      Altitude: '1,700m',
      Process: 'Yellow Honey Process',
      RoastLevel: 'Medium-Light',
      FlavorNotes: 'Golden Raisin, Red Plum, Honeycomb, Almond Butter',
    },
    featured: false,
    createdAt: '2026-01-20T08:00:00Z',
  },
  {
    id: 'prod-coffee-7',
    handle: 'signature-espresso-bar-blend',
    title: 'Signature Espresso Bar Blend',
    subtitle: 'Meticulously crafted for thick golden crema and dense chocolate praline',
    description: 'Our flagship house espresso. A balanced marriage of pulped-natural Brazil Cerrado for hazelnut base, washed Colombia Huila for milk chocolate sweetness, and a touch of Ethiopian Yirgacheffe for lemon zest vibrancy.',
    price: 18.5,
    compareAtPrice: 22.0,
    category: 'Blends',
    tags: ['blends', 'espresso', 'medium-dark', 'crema', 'bestseller'],
    images: [
      {
        id: 'img-coffee-7-1',
        url: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&w=800&q=80',
        altText: 'Double shot of espresso with marbled tiger-stripe crema',
      },
    ],
    options: [
      { name: 'Grind', values: ['Whole Bean', 'Espresso Grind'] },
      { name: 'Weight', values: ['250g', '500g', '1kg'] },
    ],
    variants: [
      {
        id: 'var-coffee-7-1',
        title: 'Whole Bean / 250g',
        sku: 'COF-BL-ESP-WB-250',
        price: 18.5,
        compareAtPrice: 22.0,
        options: { Grind: 'Whole Bean', Weight: '250g' },
        availableForSale: true,
        inventoryQuantity: 65,
      },
      {
        id: 'var-coffee-7-2',
        title: 'Espresso Grind / 250g',
        sku: 'COF-BL-ESP-EG-250',
        price: 18.5,
        compareAtPrice: 22.0,
        options: { Grind: 'Espresso Grind', Weight: '250g' },
        availableForSale: true,
        inventoryQuantity: 40,
      },
    ],
    rating: { average: 4.9, count: 94 },
    specifications: {
      Composition: '50% Brazil, 35% Colombia, 15% Ethiopia',
      RoastLevel: 'Medium-Dark',
      Extraction: '18g in, 38g out, 27 seconds',
      FlavorNotes: 'Dark Chocolate Ganache, Hazelnut Praline, Candied Lemon',
    },
    featured: false,
    createdAt: '2026-01-22T08:00:00Z',
  },
  {
    id: 'prod-coffee-8',
    handle: 'cold-brew-slow-drip-blend',
    title: 'Cold Brew Slow Drip Blend',
    subtitle: 'Coarse steep blend engineered for low-acid, velvety cold extraction',
    description: 'Designed specifically for extended 16-24 hour room temperature or cold-water immersion. Extracts rich chocolate fudge and vanilla bourbon essence with virtually zero perceived bitterness or harsh astringency.',
    price: 18.0,
    category: 'Blends',
    tags: ['blends', 'cold-brew', 'dark-roast', 'smooth'],
    images: [
      {
        id: 'img-coffee-8-1',
        url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=800&q=80',
        altText: 'Cold brew coffee poured over crystalline ice cubes in tall tumbler',
      },
    ],
    options: [
      { name: 'Grind', values: ['Whole Bean', 'Coarse Cold Brew Grind'] },
      { name: 'Weight', values: ['500g', '1kg'] },
    ],
    variants: [
      {
        id: 'var-coffee-8-1',
        title: 'Whole Bean / 500g',
        sku: 'COF-BL-CB-WB-500',
        price: 18.0,
        options: { Grind: 'Whole Bean', Weight: '500g' },
        availableForSale: true,
        inventoryQuantity: 38,
      },
    ],
    rating: { average: 4.7, count: 33 },
    specifications: {
      Composition: '60% Guatemala, 40% Sumatra',
      RoastLevel: 'Dark',
      SteepRatio: '1:8 concentrate, 1:16 ready-to-drink',
      FlavorNotes: 'Molasses, Dark Cocoa Fudge, Bourbon Vanilla',
    },
    featured: false,
    createdAt: '2026-01-24T08:00:00Z',
  },
  {
    id: 'prod-coffee-9',
    handle: 'dawn-patrol-breakfast-roast',
    title: 'Dawn Patrol Breakfast Roast',
    subtitle: 'Bright morning blend with sweet honey crisp apple and toasted almond',
    description: 'An uplifting morning companion crafted with vibrant Central American and East African components. Light on the palate with a clean honey finish that awakens the senses without overwhelming.',
    price: 17.5,
    category: 'Blends',
    tags: ['blends', 'light-roast', 'morning', 'clean'],
    images: [
      {
        id: 'img-coffee-9-1',
        url: 'https://images.unsplash.com/photo-1497636577773-f1231844b336?auto=format&fit=crop&w=800&q=80',
        altText: 'Morning light streaming over fresh ceramic mug of breakfast roast coffee',
      },
    ],
    options: [
      { name: 'Grind', values: ['Whole Bean', 'Filter Grind'] },
      { name: 'Weight', values: ['250g', '500g'] },
    ],
    variants: [
      {
        id: 'var-coffee-9-1',
        title: 'Whole Bean / 250g',
        sku: 'COF-BL-DP-WB-250',
        price: 17.5,
        options: { Grind: 'Whole Bean', Weight: '250g' },
        availableForSale: true,
        inventoryQuantity: 45,
      },
    ],
    rating: { average: 4.6, count: 28 },
    specifications: {
      Composition: '70% Guatemala, 30% Rwanda',
      RoastLevel: 'Light-Medium',
      FlavorNotes: 'Honey Crisp Apple, Toasted Almond, Meyer Lemon',
    },
    featured: false,
    createdAt: '2026-01-26T08:00:00Z',
  },
  {
    id: 'prod-coffee-10',
    handle: 'midnight-oil-french-roast',
    title: 'Midnight Oil French Roast',
    subtitle: 'Intense smoky dark roast roasted to the edge of the second crack',
    description: 'For those who crave deep intensity and lingering smoke. Slow roasted to release natural bean oils, producing a heavy, brooding cup with bittersweet dark chocolate and roasted chicory.',
    price: 18.0,
    category: 'Blends',
    tags: ['blends', 'dark-roast', 'smoky', 'intense'],
    images: [
      {
        id: 'img-coffee-10-1',
        url: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=800&q=80',
        altText: 'Dark aromatic coffee beans roasted to French roast depth',
      },
    ],
    options: [
      { name: 'Grind', values: ['Whole Bean', 'French Press'] },
      { name: 'Weight', values: ['250g', '500g'] },
    ],
    variants: [
      {
        id: 'var-coffee-10-1',
        title: 'Whole Bean / 250g',
        sku: 'COF-BL-MO-WB-250',
        price: 18.0,
        options: { Grind: 'Whole Bean', Weight: '250g' },
        availableForSale: true,
        inventoryQuantity: 27,
      },
    ],
    rating: { average: 4.7, count: 25 },
    specifications: {
      Composition: '50% Honduras, 50% Brazil',
      RoastLevel: 'French Dark',
      FlavorNotes: 'Smoky Oak, Bittersweet Cacao, Chicory, Molasses',
    },
    featured: false,
    createdAt: '2026-01-28T08:00:00Z',
  },
  {
    id: 'prod-coffee-11',
    handle: 'ceramic-v60-dripper-set',
    title: 'Ceramic V60 Dripper Set',
    subtitle: 'Artisan matte ceramic dripper with spiral ribs and heat-resistant server',
    description: 'Precision Japanese ceramic dripper featuring internal spiral ridges that maximize water turbulence and coffee expansion. Includes a 600ml borosilicate glass server and 40 unbleached filters.',
    price: 45.0,
    compareAtPrice: 52.0,
    category: 'Brew Gear',
    tags: ['brew-gear', 'pour-over', 'ceramic', 'japanese-design'],
    images: [
      {
        id: 'img-coffee-11-1',
        url: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=800&q=80',
        altText: 'White ceramic V60 pour over dripper resting on glass decanter',
      },
    ],
    options: [
      { name: 'Finish', values: ['Matte White', 'Charcoal Black', 'Terracotta'] },
    ],
    variants: [
      {
        id: 'var-coffee-11-1',
        title: 'Matte White',
        sku: 'GEAR-V60-WHT',
        price: 45.0,
        compareAtPrice: 52.0,
        options: { Finish: 'Matte White' },
        availableForSale: true,
        inventoryQuantity: 20,
      },
      {
        id: 'var-coffee-11-2',
        title: 'Charcoal Black',
        sku: 'GEAR-V60-BLK',
        price: 45.0,
        compareAtPrice: 52.0,
        options: { Finish: 'Charcoal Black' },
        availableForSale: true,
        inventoryQuantity: 15,
      },
    ],
    rating: { average: 4.9, count: 58 },
    specifications: {
      Material: 'Arita-ware High Temperature Ceramic',
      Capacity: '1 - 4 Cups (Size 02)',
      Compatibility: 'Standard 02 Cone Filters',
      Care: 'Dishwasher Safe',
    },
    featured: false,
    createdAt: '2026-01-30T08:00:00Z',
  },
  {
    id: 'prod-coffee-12',
    handle: 'precision-burr-hand-grinder',
    title: 'Precision Burr Hand Grinder',
    subtitle: 'CNC machined stainless steel 38mm conical burrs with dual ball bearings',
    description: 'Experience ultra-uniform grind consistency anywhere. The calibrated stepped adjustment dial allows micro-fine adjustments from Turkish and espresso to coarse cold brew with near-zero fines generation.',
    price: 89.0,
    compareAtPrice: 105.0,
    category: 'Brew Gear',
    tags: ['brew-gear', 'grinder', 'stainless-steel', 'manual-brew'],
    images: [
      {
        id: 'img-coffee-12-1',
        url: 'https://images.unsplash.com/photo-1517668808822-9ebb02ae2a0e?auto=format&fit=crop&w=800&q=80',
        altText: 'Machined stainless steel hand coffee grinder with wooden crank knob',
      },
    ],
    options: [
      { name: 'Color', values: ['Space Grey', 'Brushed Silver'] },
    ],
    variants: [
      {
        id: 'var-coffee-12-1',
        title: 'Space Grey',
        sku: 'GEAR-GRD-GRY',
        price: 89.0,
        compareAtPrice: 105.0,
        options: { Color: 'Space Grey' },
        availableForSale: true,
        inventoryQuantity: 14,
      },
    ],
    rating: { average: 4.8, count: 44 },
    specifications: {
      BurrType: '38mm 420 Stainless Steel Conical',
      Capacity: '30g Beans',
      Bearings: 'Dual Precision Stainless Bearings',
      Weight: '460g',
    },
    featured: false,
    createdAt: '2026-02-01T08:00:00Z',
  },
  {
    id: 'prod-coffee-13',
    handle: 'gooseneck-temperature-kettle',
    title: 'Gooseneck Temperature Kettle',
    subtitle: 'Variable 1-degree temperature control with ergonomic counterbalanced handle',
    description: 'The definitive pour-over pouring instrument. Precision curved spout delivers a steady, laminar 90-degree flow rate. Features a 1200W rapid heating element and a 60-minute temperature hold function.',
    price: 135.0,
    compareAtPrice: 155.0,
    category: 'Brew Gear',
    tags: ['brew-gear', 'kettle', 'electric', 'precision'],
    images: [
      {
        id: 'img-coffee-13-1',
        url: 'https://images.unsplash.com/photo-1570968915860-54d5c301fa9f?auto=format&fit=crop&w=800&q=80',
        altText: 'Matte black electric gooseneck kettle pouring hot water with surgical precision',
      },
    ],
    options: [
      { name: 'Finish', values: ['Matte Black', 'Brushed Copper'] },
    ],
    variants: [
      {
        id: 'var-coffee-13-1',
        title: 'Matte Black',
        sku: 'GEAR-KET-BLK',
        price: 135.0,
        compareAtPrice: 155.0,
        options: { Finish: 'Matte Black' },
        availableForSale: true,
        inventoryQuantity: 12,
      },
    ],
    rating: { average: 4.9, count: 62 },
    specifications: {
      Power: '1200W Rapid Boil',
      Capacity: '900ml',
      TemperatureRange: '40°C - 100°C (104°F - 212°F)',
      Materials: '304 Food-Grade Stainless Steel Body',
    },
    featured: false,
    createdAt: '2026-02-03T08:00:00Z',
  },
  {
    id: 'prod-coffee-14',
    handle: 'double-walled-glass-server',
    title: 'Double-Walled Glass Server',
    subtitle: 'Hand-blown thermal insulating borosilicate glass with ergonomic lip',
    description: 'Keep your brewed coffee hot while enjoying total visual clarity. The dual glass walls prevent condensation on the exterior while insulating hot liquid for up to 45 minutes.',
    price: 32.0,
    category: 'Brew Gear',
    tags: ['brew-gear', 'glassware', 'server', 'pour-over'],
    images: [
      {
        id: 'img-coffee-14-1',
        url: 'https://images.unsplash.com/photo-1517256064527-09c73fc73e38?auto=format&fit=crop&w=800&q=80',
        altText: 'Double-walled glass coffee server filled with freshly brewed golden coffee',
      },
    ],
    options: [
      { name: 'Capacity', values: ['500ml', '800ml'] },
    ],
    variants: [
      {
        id: 'var-coffee-14-1',
        title: '500ml',
        sku: 'GEAR-SRV-500',
        price: 32.0,
        options: { Capacity: '500ml' },
        availableForSale: true,
        inventoryQuantity: 25,
      },
    ],
    rating: { average: 4.7, count: 29 },
    specifications: {
      Material: 'Hand-blown Borosilicate Glass',
      Capacity: '500ml (2 Cups)',
      ThermalRating: '-20°C to 150°C',
    },
    featured: false,
    createdAt: '2026-02-05T08:00:00Z',
  },
  {
    id: 'prod-coffee-15',
    handle: 'monthly-roasters-selection-subscription',
    title: "Monthly Roaster's Selection Subscription",
    subtitle: 'Two rotating seasonal micro-lots delivered fresh to your door each month',
    description: 'Curated by our Master Roaster. Every month you will receive two 250g bags of freshly harvested, limited release micro-lots accompanied by origin farm stories and custom brew recipes.',
    price: 38.0,
    compareAtPrice: 46.0,
    category: 'Subscriptions',
    tags: ['subscriptions', 'curated', 'monthly', 'free-shipping', 'bestseller'],
    images: [
      {
        id: 'img-coffee-15-1',
        url: 'https://images.unsplash.com/photo-1524350876685-274059332603?auto=format&fit=crop&w=800&q=80',
        altText: 'Two craft coffee subscription bags packed in recycled cardboard box with dried coffee branch',
      },
    ],
    options: [
      { name: 'Grind', values: ['Whole Bean', 'Filter Grind', 'Espresso Grind'] },
      { name: 'RoastPreference', values: ['Light & Floral', 'Medium & Balanced', 'Roaster Choice'] },
    ],
    variants: [
      {
        id: 'var-coffee-15-1',
        title: 'Whole Bean / Roaster Choice',
        sku: 'SUB-MON-WB-RC',
        price: 38.0,
        compareAtPrice: 46.0,
        options: { Grind: 'Whole Bean', RoastPreference: 'Roaster Choice' },
        availableForSale: true,
        inventoryQuantity: 99,
      },
      {
        id: 'var-coffee-15-2',
        title: 'Filter Grind / Light & Floral',
        sku: 'SUB-MON-FG-LF',
        price: 38.0,
        compareAtPrice: 46.0,
        options: { Grind: 'Filter Grind', RoastPreference: 'Light & Floral' },
        availableForSale: true,
        inventoryQuantity: 80,
      },
    ],
    rating: { average: 5.0, count: 112 },
    specifications: {
      Frequency: 'Monthly (Pause or Cancel Anytime)',
      Volume: '2 x 250g Bags (approx. 35 cups)',
      Shipping: 'Included (Free Courier Delivery)',
      Freshness: 'Roasted within 48 hours of dispatch',
    },
    featured: false,
    createdAt: '2026-02-07T08:00:00Z',
  },
  {
    id: 'prod-coffee-16',
    handle: 'single-origin-espresso-club-subscription',
    title: 'Single Origin Espresso Club Subscription',
    subtitle: 'Three 250g bags of vibrant single-origin coffees roasted specifically for espresso',
    description: 'Expand your espresso horizon. Exploring single-origin espresso unlocks bright fruit notes, sparkling acidity, and unique mouthfeel that commercial blends simply cannot replicate.',
    price: 54.0,
    compareAtPrice: 66.0,
    category: 'Subscriptions',
    tags: ['subscriptions', 'espresso', 'single-origin', 'monthly'],
    images: [
      {
        id: 'img-coffee-16-1',
        url: 'https://images.unsplash.com/photo-1442512595331-e89e73853f31?auto=format&fit=crop&w=800&q=80',
        altText: 'Specialty espresso extraction flowing steadily from naked bottomless portafilter',
      },
    ],
    options: [
      { name: 'Grind', values: ['Whole Bean', 'Calibrated Espresso Grind'] },
    ],
    variants: [
      {
        id: 'var-coffee-16-1',
        title: 'Whole Bean',
        sku: 'SUB-ESP-WB',
        price: 54.0,
        compareAtPrice: 66.0,
        options: { Grind: 'Whole Bean' },
        availableForSale: true,
        inventoryQuantity: 60,
      },
    ],
    rating: { average: 4.9, count: 57 },
    specifications: {
      Frequency: 'Monthly',
      Volume: '3 x 250g Bags (approx. 50 double shots)',
      DialInGuide: 'Custom grind and extraction recipe cards included',
    },
    featured: false,
    createdAt: '2026-02-09T08:00:00Z',
  },
];

export default coffeeProducts;
