import { Product } from '../../types/product';

export const jewelryProducts: Product[] = [
  {
    id: 'prod-jewelry-1',
    handle: 'solitaire-diamond-constellation-ring',
    title: 'Solitaire Diamond Constellation Ring',
    subtitle: '1.50 Carat Round Brilliant Diamond on 6-prong platinum cathedral band',
    description: 'A benchmark of classical Parisian elegance. Hand-set with a GIA-certified 1.50ct Round Brilliant natural diamond (F color, VVS1 clarity, Triple Excellent cut). Mounted on a knife-edge platinum 950 band with pavé gallery accents.',
    price: 3450.0,
    compareAtPrice: 3950.0,
    category: 'Rings',
    tags: ['rings', 'diamond', 'platinum', 'engagement', 'bestseller'],
    images: [
      {
        id: 'img-jewelry-1-1',
        url: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=800&q=80',
        altText: 'Solitaire diamond engagement ring sparkling against dark black velvet box',
      },
      {
        id: 'img-jewelry-1-2',
        url: 'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?auto=format&fit=crop&w=800&q=80',
        altText: 'Side angle of platinum ring showing delicate 6-prong diamond cathedral setting',
      },
    ],
    options: [
      { name: 'Metal', values: ['Platinum 950', '18K Yellow Gold', '18K Rose Gold'] },
      { name: 'Size', values: ['5', '6', '7', '8'] },
    ],
    variants: [
      {
        id: 'var-jewelry-1-1',
        title: 'Platinum 950 / 6',
        sku: 'JWL-RNG-SOL-PLT-6',
        price: 3450.0,
        compareAtPrice: 3950.0,
        options: { Metal: 'Platinum 950', Size: '6' },
        availableForSale: true,
        inventoryQuantity: 5,
      },
      {
        id: 'var-jewelry-1-2',
        title: 'Platinum 950 / 7',
        sku: 'JWL-RNG-SOL-PLT-7',
        price: 3450.0,
        compareAtPrice: 3950.0,
        options: { Metal: 'Platinum 950', Size: '7' },
        availableForSale: true,
        inventoryQuantity: 7,
      },
      {
        id: 'var-jewelry-1-3',
        title: '18K Yellow Gold / 6',
        sku: 'JWL-RNG-SOL-YG-6',
        price: 3200.0,
        compareAtPrice: 3700.0,
        options: { Metal: '18K Yellow Gold', Size: '6' },
        availableForSale: true,
        inventoryQuantity: 4,
      },
    ],
    rating: { average: 5.0, count: 38 },
    specifications: {
      CenterStone: '1.50 Carat Natural Diamond',
      ColorClarity: 'F Color, VVS1 Clarity',
      CutGrade: 'GIA Triple Excellent (Cut, Polish, Symmetry)',
      MetalPurity: 'Platinum 950 (Hallmarked)',
      Certification: 'GIA Diamond Dossier Inscribed',
    },
    featured: true,
    createdAt: '2026-01-05T08:00:00Z',
  },
  {
    id: 'prod-jewelry-2',
    handle: 'aura-pave-diamond-band',
    title: 'Aura Pavé Diamond Band',
    subtitle: 'Micro-scalloped eternity ring set with 0.85ct brilliant pavé diamonds',
    description: 'Continuous ribbons of brilliance. Each microscopic round diamond is individually hand-seated into 18k solid gold with minimal metal intrusion, maximizing scintillation from every vantage angle.',
    price: 880.0,
    compareAtPrice: 1020.0,
    category: 'Rings',
    tags: ['rings', 'pave', 'gold', 'eternity', 'stacking'],
    images: [
      {
        id: 'img-jewelry-2-1',
        url: 'https://images.unsplash.com/photo-1598560917505-59a3ad559071?auto=format&fit=crop&w=800&q=80',
        altText: 'Stack of delicate 18k gold diamond pavé eternity bands resting on stone slab',
      },
    ],
    options: [
      { name: 'Metal', values: ['18K Yellow Gold', '18K White Gold', '18K Rose Gold'] },
      { name: 'Size', values: ['5', '6', '7', '8'] },
    ],
    variants: [
      {
        id: 'var-jewelry-2-1',
        title: '18K Yellow Gold / 6',
        sku: 'JWL-RNG-AUR-YG-6',
        price: 880.0,
        compareAtPrice: 1020.0,
        options: { Metal: '18K Yellow Gold', Size: '6' },
        availableForSale: true,
        inventoryQuantity: 14,
      },
      {
        id: 'var-jewelry-2-2',
        title: '18K White Gold / 7',
        sku: 'JWL-RNG-AUR-WG-7',
        price: 880.0,
        compareAtPrice: 1020.0,
        options: { Metal: '18K White Gold', Size: '7' },
        availableForSale: true,
        inventoryQuantity: 12,
      },
    ],
    rating: { average: 4.9, count: 46 },
    specifications: {
      DiamondWeight: '0.85 Total Carat Weight',
      ColorClarity: 'G-H Color, VS Clarity',
      Width: '1.8mm Delicate Profile',
    },
    featured: true,
    createdAt: '2026-01-08T08:00:00Z',
  },
  {
    id: 'prod-jewelry-3',
    handle: 'baguette-eternity-wedding-band',
    title: 'Baguette Eternity Wedding Band',
    subtitle: 'Channel-set step cut baguette diamonds in 18k solid gold',
    description: 'Clean architectural geometry evoking Art Deco sophistication. Calibrated baguette diamonds are seamlessly aligned in a secure channel setting, offering mirror-like step-cut reflections.',
    price: 1450.0,
    category: 'Rings',
    tags: ['rings', 'baguette', 'art-deco', 'wedding'],
    images: [
      {
        id: 'img-jewelry-3-1',
        url: 'https://images.unsplash.com/photo-1543290104-5853b0b9a896?auto=format&fit=crop&w=800&q=80',
        altText: 'Art Deco baguette diamond eternity ring displayed in warm sunlight',
      },
    ],
    options: [
      { name: 'Metal', values: ['18K Yellow Gold', 'Platinum 950'] },
      { name: 'Size', values: ['6', '7', '8'] },
    ],
    variants: [
      {
        id: 'var-jewelry-3-1',
        title: '18K Yellow Gold / 6',
        sku: 'JWL-RNG-BAG-YG-6',
        price: 1450.0,
        options: { Metal: '18K Yellow Gold', Size: '6' },
        availableForSale: true,
        inventoryQuantity: 9,
      },
    ],
    rating: { average: 4.8, count: 24 },
    specifications: {
      TotalCarat: '1.20 Carats Step-Cut Baguettes',
      Setting: 'Precision Channel Set',
      BandWidth: '2.4mm',
    },
    featured: false,
    createdAt: '2026-01-10T08:00:00Z',
  },
  {
    id: 'prod-jewelry-4',
    handle: 'cushion-cut-tanzanite-cocktail-ring',
    title: 'Cushion Cut Tanzanite Cocktail Ring',
    subtitle: '4.20 Carat intense royal blue Tanzanite framed by brilliant diamond halo',
    description: 'Unearthed from the foothills of Mount Kilimanjaro. This exceptional untreated cushion-cut tanzanite flashes vibrant violet-blue pleochroism, elevated by a halo of 28 micro-pavé diamonds.',
    price: 2800.0,
    compareAtPrice: 3200.0,
    category: 'Rings',
    tags: ['rings', 'tanzanite', 'gemstone', 'cocktail', 'luxury'],
    images: [
      {
        id: 'img-jewelry-4-1',
        url: 'https://images.unsplash.com/photo-1608042314453-ae338d80c427?auto=format&fit=crop&w=800&q=80',
        altText: 'Deep blue cushion cut gemstone cocktail ring with sparkling diamond halo',
      },
    ],
    options: [
      { name: 'Metal', values: ['18K White Gold', 'Platinum 950'] },
      { name: 'Size', values: ['6', '7'] },
    ],
    variants: [
      {
        id: 'var-jewelry-4-1',
        title: '18K White Gold / 7',
        sku: 'JWL-RNG-TNZ-WG-7',
        price: 2800.0,
        compareAtPrice: 3200.0,
        options: { Metal: '18K White Gold', Size: '7' },
        availableForSale: true,
        inventoryQuantity: 3,
      },
    ],
    rating: { average: 5.0, count: 18 },
    specifications: {
      CenterGem: '4.20ct Natural Tanzanite (AAA Royal Blue)',
      HaloDiamonds: '0.42ct Round Brilliants',
      Origin: 'Merelani Hills, Tanzania',
    },
    featured: false,
    createdAt: '2026-01-12T08:00:00Z',
  },
  {
    id: 'prod-jewelry-5',
    handle: 'emerald-cut-colombian-sapphire-pendant',
    title: 'Emerald Cut Colombian Sapphire Pendant',
    subtitle: 'Cornflower blue sapphire pendant suspended from 18k gold Venetian chain',
    description: 'A mesmerizing 2.10ct unheated sapphire carved with clean emerald step cuts. Encased in a solid 18k yellow gold bezel with an integrated bail and a delicate 45cm adjustable Venetian chain.',
    price: 2150.0,
    compareAtPrice: 2500.0,
    category: 'Necklaces',
    tags: ['necklaces', 'sapphire', 'pendant', 'gold', 'bestseller'],
    images: [
      {
        id: 'img-jewelry-5-1',
        url: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=80',
        altText: 'Gold chain necklace with radiant blue sapphire pendant resting on silk',
      },
    ],
    options: [
      { name: 'Metal', values: ['18K Yellow Gold', '18K White Gold'] },
      { name: 'ChainLength', values: ['42cm (16.5in)', '45cm (18in)'] },
    ],
    variants: [
      {
        id: 'var-jewelry-5-1',
        title: '18K Yellow Gold / 45cm',
        sku: 'JWL-NCK-SAP-YG-45',
        price: 2150.0,
        compareAtPrice: 2500.0,
        options: { Metal: '18K Yellow Gold', ChainLength: '45cm (18in)' },
        availableForSale: true,
        inventoryQuantity: 6,
      },
    ],
    rating: { average: 4.9, count: 32 },
    specifications: {
      Gemstone: '2.10 Carat Natural Ceylon Sapphire',
      ChainType: '1.2mm Solid Venetian Box Chain',
      Clasp: 'Lobster Claw with Hallmarked L\'Étoile Plaque',
    },
    featured: true,
    createdAt: '2026-01-15T08:00:00Z',
  },
  {
    id: 'prod-jewelry-6',
    handle: 'cascade-tahitian-pearl-necklace',
    title: 'Cascade Tahitian Pearl Necklace',
    subtitle: 'Graduated peacock black Tahitian cultured pearls with 18k diamond clasp',
    description: 'Harvested from the warm lagoons of French Polynesia. 39 lustrous pearls graduating from 10mm to 13.5mm with vibrant overtone hues of peacock green, aubergine, and platinum silver.',
    price: 3600.0,
    category: 'Necklaces',
    tags: ['necklaces', 'pearl', 'tahitian', 'luxury', 'statement'],
    images: [
      {
        id: 'img-jewelry-6-1',
        url: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=800&q=80',
        altText: 'Strand of shimmering peacock green Tahitian black pearls with diamond clasp',
      },
    ],
    options: [
      { name: 'Length', values: ['45cm Princess', '50cm Matinee'] },
    ],
    variants: [
      {
        id: 'var-jewelry-6-1',
        title: '45cm Princess',
        sku: 'JWL-NCK-PRL-45',
        price: 3600.0,
        options: { Length: '45cm Princess' },
        availableForSale: true,
        inventoryQuantity: 4,
      },
    ],
    rating: { average: 5.0, count: 21 },
    specifications: {
      PearlGrade: 'AAA Luster & Surface Purity',
      Diameter: '10.0mm - 13.5mm Graduated',
      Clasp: '18K White Gold Ball Clasp with 0.15ct Diamonds',
      Knotting: 'Double Knotted on Pure Silk Thread',
    },
    featured: true,
    createdAt: '2026-01-18T08:00:00Z',
  },
  {
    id: 'prod-jewelry-7',
    handle: 'rose-gold-starlight-lariat-necklace',
    title: 'Rose Gold Starlight Lariat Necklace',
    subtitle: 'Adjustable 18k rose gold slider necklace with diamond starburst pendant',
    description: 'Fluid drape that adjusts effortlessly with an internal silicone slider ball. Embellished with celestial diamond star motifs that catch the light with subtle kinetic movement.',
    price: 980.0,
    compareAtPrice: 1150.0,
    category: 'Necklaces',
    tags: ['necklaces', 'rose-gold', 'diamond', 'lariat', 'celestial'],
    images: [
      {
        id: 'img-jewelry-7-1',
        url: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=80',
        altText: 'Delicate rose gold diamond lariat necklace cascading over collarbone',
      },
    ],
    options: [
      { name: 'Metal', values: ['18K Rose Gold', '18K Yellow Gold'] },
    ],
    variants: [
      {
        id: 'var-jewelry-7-1',
        title: '18K Rose Gold',
        sku: 'JWL-NCK-LAR-RG',
        price: 980.0,
        compareAtPrice: 1150.0,
        options: { Metal: '18K Rose Gold' },
        availableForSale: true,
        inventoryQuantity: 11,
      },
    ],
    rating: { average: 4.8, count: 35 },
    specifications: {
      DiamondAccents: '0.28ct Round Brilliants (F-G, VS)',
      Chain: '55cm Total Length with Adjustable Slider',
      GoldWeight: '4.8g 18k Rose Gold',
    },
    featured: false,
    createdAt: '2026-01-20T08:00:00Z',
  },
  {
    id: 'prod-jewelry-8',
    handle: 'opulence-ruby-choker',
    title: 'Opulence Ruby Choker',
    subtitle: 'Collet-set oval pigeon blood Burmese rubies alternating with rose cut diamonds',
    description: 'An homage to 19th century Belle Époque majesty. 12 vivid unheated oval rubies individually enclosed in hand-engraved collet cups, linked together in supple articulating harmony.',
    price: 3750.0,
    category: 'Necklaces',
    tags: ['necklaces', 'ruby', 'choker', 'antique-revival', 'high-jewelry'],
    images: [
      {
        id: 'img-jewelry-8-1',
        url: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=800&q=80',
        altText: 'Antique-inspired ruby and diamond choker necklace laid out on dark velvet',
      },
    ],
    options: [
      { name: 'Length', values: ['38cm Choker', '42cm Collar'] },
    ],
    variants: [
      {
        id: 'var-jewelry-8-1',
        title: '38cm Choker',
        sku: 'JWL-NCK-RBY-38',
        price: 3750.0,
        options: { Length: '38cm Choker' },
        availableForSale: true,
        inventoryQuantity: 2,
      },
    ],
    rating: { average: 5.0, count: 14 },
    specifications: {
      Rubies: '5.40ct Total Weight (Pigeon Blood Red)',
      Diamonds: '1.80ct Rose-Cut Diamonds',
      Metal: '18K Yellow Gold with Oxidized Silver Accents',
    },
    featured: false,
    createdAt: '2026-01-22T08:00:00Z',
  },
  {
    id: 'prod-jewelry-9',
    handle: 'tahitian-south-sea-pearl-earrings',
    title: 'Tahitian South Sea Pearl Earrings',
    subtitle: '11mm round peacock pearls hanging from diamond huggie hoops in 18k gold',
    description: 'Understated luxury for day-to-evening transitions. Detachable Tahitian pearls allow the brilliant diamond pavé huggies to be worn independently as minimalist hoops.',
    price: 890.0,
    compareAtPrice: 1050.0,
    category: 'Earrings',
    tags: ['earrings', 'pearl', 'tahitian', 'huggie', 'convertible'],
    images: [
      {
        id: 'img-jewelry-9-1',
        url: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=800&q=80',
        altText: 'Lustrous black Tahitian pearl drop earrings suspended from diamond huggies',
      },
    ],
    options: [
      { name: 'Metal', values: ['18K Yellow Gold', '18K White Gold'] },
    ],
    variants: [
      {
        id: 'var-jewelry-9-1',
        title: '18K Yellow Gold',
        sku: 'JWL-EAR-PRL-YG',
        price: 890.0,
        compareAtPrice: 1050.0,
        options: { Metal: '18K Yellow Gold' },
        availableForSale: true,
        inventoryQuantity: 12,
      },
    ],
    rating: { average: 4.9, count: 40 },
    specifications: {
      Pearls: 'Pair 11.0mm Round Cultured Tahitian Pearls',
      Diamonds: '0.18ct Micro-Pavé on Hoops',
      Convertible: 'Removable Pearl Charms',
    },
    featured: false,
    createdAt: '2026-01-24T08:00:00Z',
  },
  {
    id: 'prod-jewelry-10',
    handle: 'lumiere-sapphire-drop-earrings',
    title: 'Lumière Sapphire Drop Earrings',
    subtitle: 'Pear-shaped royal blue sapphires dangling from articulated diamond links',
    description: 'Dynamic movement that catches candlelight at every turn. Twin matched 1.5ct pear sapphires dance gracefully beneath articulated diamond links with secure French leverbacks.',
    price: 1950.0,
    category: 'Earrings',
    tags: ['earrings', 'sapphire', 'drop-earrings', 'fine-jewelry'],
    images: [
      {
        id: 'img-jewelry-10-1',
        url: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=80',
        altText: 'Pair of sapphire and diamond drop earrings with French wire backing',
      },
    ],
    options: [
      { name: 'Metal', values: ['18K White Gold', 'Platinum 950'] },
    ],
    variants: [
      {
        id: 'var-jewelry-10-1',
        title: '18K White Gold',
        sku: 'JWL-EAR-SAP-WG',
        price: 1950.0,
        options: { Metal: '18K White Gold' },
        availableForSale: true,
        inventoryQuantity: 7,
      },
    ],
    rating: { average: 4.9, count: 27 },
    specifications: {
      Sapphires: '3.00 Total Carat Weight Matched Pear Cuts',
      Diamonds: '0.45ct Round Brilliants',
      Closure: 'Secure Leverback Safety Clasp',
    },
    featured: false,
    createdAt: '2026-01-26T08:00:00Z',
  },
  {
    id: 'prod-jewelry-11',
    handle: 'hammered-18k-yellow-gold-hoops',
    title: 'Hammered 18K Yellow Gold Hoops',
    subtitle: 'Hand-chiseled 25mm hollow tube hoops with satin-brushed gold finish',
    description: 'Lightweight volume sculpted for all-day comfort. Master craftsmen hammer each surface by hand to produce organic, light-diffusing facets across the curving circular arc.',
    price: 640.0,
    compareAtPrice: 750.0,
    category: 'Earrings',
    tags: ['earrings', 'gold', 'hoops', 'hammered', 'everyday'],
    images: [
      {
        id: 'img-jewelry-11-1',
        url: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=800&q=80',
        altText: 'Pair of warm hammered 18k yellow gold hoop earrings resting on linen',
      },
    ],
    options: [
      { name: 'Diameter', values: ['20mm Petite', '25mm Classic', '32mm Bold'] },
    ],
    variants: [
      {
        id: 'var-jewelry-11-1',
        title: '25mm Classic',
        sku: 'JWL-EAR-HOP-25',
        price: 640.0,
        compareAtPrice: 750.0,
        options: { Diameter: '25mm Classic' },
        availableForSale: true,
        inventoryQuantity: 20,
      },
    ],
    rating: { average: 4.8, count: 52 },
    specifications: {
      Metal: 'Solid 18K Yellow Gold (750 Purity)',
      Weight: '3.6g (Ultra-Lightweight Hollow Core)',
      Closure: 'Hidden Click-In Post',
    },
    featured: false,
    createdAt: '2026-01-28T08:00:00Z',
  },
  {
    id: 'prod-jewelry-12',
    handle: 'diamond-waterfall-drop-earrings',
    title: 'Diamond Waterfall Drop Earrings',
    subtitle: 'Cascading graduated marquise and round diamond chandelier drops',
    description: 'An unforgettable evening statement. 52 individually claw-set marquise and brilliant-cut diamonds form an undulating cascade reminiscent of cascading crystal water droplets.',
    price: 3200.0,
    category: 'Earrings',
    tags: ['earrings', 'diamond', 'chandelier', 'red-carpet', 'high-jewelry'],
    images: [
      {
        id: 'img-jewelry-12-1',
        url: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=80',
        altText: 'Diamond chandelier waterfall drop earrings shimmering under evening spotlight',
      },
    ],
    options: [
      { name: 'Metal', values: ['18K White Gold', 'Platinum 950'] },
    ],
    variants: [
      {
        id: 'var-jewelry-12-1',
        title: 'Platinum 950',
        sku: 'JWL-EAR-WTF-PLT',
        price: 3200.0,
        options: { Metal: 'Platinum 950' },
        availableForSale: true,
        inventoryQuantity: 3,
      },
    ],
    rating: { average: 5.0, count: 16 },
    specifications: {
      DiamondCarat: '2.85ct Total Weight (E-F Color, VVS Clarity)',
      Length: '45mm Drop',
      Backing: 'Heavy Friction Post with Comfort Clutch',
    },
    featured: false,
    createdAt: '2026-01-30T08:00:00Z',
  },
  {
    id: 'prod-jewelry-13',
    handle: 'floating-diamond-tennis-bracelet',
    title: 'Floating Diamond Tennis Bracelet',
    subtitle: '4.00 Total Carat Weight 4-prong continuous line bracelet with double safety lock',
    description: 'The quintessential luxury jewelry cornerstone. Hand-strung with 56 identical round brilliant cut natural diamonds in low-profile basket settings that slide fluidly along the wrist.',
    price: 2950.0,
    compareAtPrice: 3400.0,
    category: 'High Jewelry',
    tags: ['high-jewelry', 'bracelet', 'tennis-bracelet', 'diamond', 'bestseller'],
    images: [
      {
        id: 'img-jewelry-13-1',
        url: 'https://images.unsplash.com/photo-1611591475883-9b6999fa5113?auto=format&fit=crop&w=800&q=80',
        altText: 'Sparkling diamond tennis bracelet draped gracefully over wrist',
      },
    ],
    options: [
      { name: 'Metal', values: ['18K White Gold', '18K Yellow Gold', 'Platinum 950'] },
      { name: 'WristLength', values: ['16.5cm (6.5in)', '18cm (7.0in)'] },
    ],
    variants: [
      {
        id: 'var-jewelry-13-1',
        title: '18K White Gold / 18cm',
        sku: 'JWL-BRC-TNS-WG-18',
        price: 2950.0,
        compareAtPrice: 3400.0,
        options: { Metal: '18K White Gold', WristLength: '18cm (7.0in)' },
        availableForSale: true,
        inventoryQuantity: 8,
      },
    ],
    rating: { average: 4.9, count: 64 },
    specifications: {
      CaratWeight: '4.00ct Total Round Brilliants',
      DiamondSpecs: 'F-G Color, VS Clarity',
      Clasp: 'Concealed Box Clasp with Dual Figure-8 Safeties',
    },
    featured: false,
    createdAt: '2026-02-01T08:00:00Z',
  },
  {
    id: 'prod-jewelry-14',
    handle: 'constellation-gold-bangle',
    title: 'Constellation Gold Bangle',
    subtitle: 'Hinged oval solid 18k gold bangle set with flush gypsy-set diamonds',
    description: 'An ergonomic oval profile designed to hug the wrist contour without rolling. Features 9 scattered star-cut gypsy set diamonds across the satin-finished gold crown.',
    price: 1850.0,
    category: 'High Jewelry',
    tags: ['high-jewelry', 'bangle', 'gold', 'bracelet', 'stackable'],
    images: [
      {
        id: 'img-jewelry-14-1',
        url: 'https://images.unsplash.com/photo-1611591475883-9b6999fa5113?auto=format&fit=crop&w=800&q=80',
        altText: 'Satin finished 18k yellow gold bangle with star-set sparkling diamonds',
      },
    ],
    options: [
      { name: 'Metal', values: ['18K Yellow Gold', '18K Rose Gold'] },
      { name: 'Size', values: ['Small (16cm)', 'Medium (17.5cm)'] },
    ],
    variants: [
      {
        id: 'var-jewelry-14-1',
        title: '18K Yellow Gold / Medium',
        sku: 'JWL-BNG-CST-YG-M',
        price: 1850.0,
        options: { Metal: '18K Yellow Gold', Size: 'Medium (17.5cm)' },
        availableForSale: true,
        inventoryQuantity: 9,
      },
    ],
    rating: { average: 4.8, count: 29 },
    specifications: {
      GoldPurity: '18K Solid Gold (14.2g)',
      Diamonds: '9 Flush Star Gypsy Settings (0.36ct Total)',
      Mechanism: 'Concealed Push-Button Hinge',
    },
    featured: false,
    createdAt: '2026-02-03T08:00:00Z',
  },
  {
    id: 'prod-jewelry-15',
    handle: 'heritage-emerald-pendant',
    title: 'Heritage Emerald Pendant',
    subtitle: '3.10 Carat Colombian minor oil emerald surrounded by diamond baguette sunburst',
    description: 'Sourced from the historic Muzo mines of Colombia. Renowned for their glowing green crystalline fire, framed by radiating diamond baguettes on a heavy wheat chain.',
    price: 3800.0,
    category: 'High Jewelry',
    tags: ['high-jewelry', 'emerald', 'pendant', 'collector'],
    images: [
      {
        id: 'img-jewelry-15-1',
        url: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=80',
        altText: 'Magnificent glowing green Colombian emerald pendant surrounded by diamond rays',
      },
    ],
    options: [
      { name: 'Metal', values: ['18K Yellow Gold with Platinum Bezel'] },
    ],
    variants: [
      {
        id: 'var-jewelry-15-1',
        title: '18K Yellow Gold',
        sku: 'JWL-PDT-EMR-YG',
        price: 3800.0,
        options: { Metal: '18K Yellow Gold with Platinum Bezel' },
        availableForSale: true,
        inventoryQuantity: 2,
      },
    ],
    rating: { average: 5.0, count: 12 },
    specifications: {
      Emerald: '3.10ct Muzo Emerald (Minor Cedar Oil Only)',
      Certification: 'Gübelin Gem Lab Report',
      Diamonds: '1.15ct Tapered Baguettes',
    },
    featured: false,
    createdAt: '2026-02-05T08:00:00Z',
  },
  {
    id: 'prod-jewelry-16',
    handle: 'celestial-starburst-brooch',
    title: 'Celestial Starburst Brooch',
    subtitle: 'Articulated platinum brooch with 3.5ct mixed cut diamonds and central natural pearl',
    description: 'A museum-tier archival jewel. Convertible between an opulent evening brooch and a dramatic pendant on a velvet ribbon. Inspired by astronomical drawings from the Paris Observatory.',
    price: 3400.0,
    compareAtPrice: 3900.0,
    category: 'High Jewelry',
    tags: ['high-jewelry', 'brooch', 'convertible', 'pearl', 'collector'],
    images: [
      {
        id: 'img-jewelry-16-1',
        url: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=800&q=80',
        altText: 'Intricate diamond starburst brooch with central glowing pearl on midnight silk',
      },
    ],
    options: [
      { name: 'Finish', values: ['Platinum 950'] },
    ],
    variants: [
      {
        id: 'var-jewelry-16-1',
        title: 'Platinum 950',
        sku: 'JWL-BRH-STR-PLT',
        price: 3400.0,
        compareAtPrice: 3900.0,
        options: { Finish: 'Platinum 950' },
        availableForSale: true,
        inventoryQuantity: 3,
      },
    ],
    rating: { average: 4.9, count: 15 },
    specifications: {
      Diamonds: '3.50ct Old European and Brilliant Cuts',
      CenterPearl: '9.2mm Natural Saltwater Pearl',
      Versatility: 'Convertible Brooch Pin and Hidden Pendant Bail',
    },
    featured: false,
    createdAt: '2026-02-07T08:00:00Z',
  },
];

export default jewelryProducts;
