import { Product } from '../../types/product';

export const electronicsProducts: Product[] = [
  {
    id: 'prod-elec-1',
    handle: 'apex-pro-75-mechanical-keyboard',
    title: 'Apex Pro 75% Mechanical Keyboard',
    subtitle: 'Magnetic Hall-effect switches with 0.1mm - 4.0mm adjustable rapid trigger',
    description: 'Precision competitive gaming keyboard machined from a solid 6063 aerospace aluminum block. Features gasket-mounted FR4 switch plate, magnetic Hall effect analog switches with per-key rapid trigger, and 8,000Hz USB polling.',
    price: 199.0,
    compareAtPrice: 229.0,
    category: 'Keyboards',
    tags: ['keyboards', 'hall-effect', 'rapid-trigger', 'esports', 'bestseller'],
    images: [
      {
        id: 'img-elec-1-1',
        url: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80',
        altText: 'Custom 75 percent mechanical keyboard with cyber cyan underglow on dark desk',
      },
      {
        id: 'img-elec-1-2',
        url: 'https://images.unsplash.com/photo-1595225476474-87563907a212?auto=format&fit=crop&w=800&q=80',
        altText: 'Close up view of PBT double-shot keycaps and brushed aluminum keyboard bevel',
      },
    ],
    options: [
      { name: 'Finish', values: ['Cyber Cyan', 'Matte Black', 'Lunar White'] },
      { name: 'SwitchType', values: ['Magnetic Hall Effect', 'Pre-Lubed Linear 45g'] },
    ],
    variants: [
      {
        id: 'var-elec-1-1',
        title: 'Cyber Cyan / Magnetic Hall Effect',
        sku: 'NEX-KBD-75-CYN-HE',
        price: 199.0,
        compareAtPrice: 229.0,
        options: { Finish: 'Cyber Cyan', SwitchType: 'Magnetic Hall Effect' },
        availableForSale: true,
        inventoryQuantity: 32,
        imageUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80',
      },
      {
        id: 'var-elec-1-2',
        title: 'Matte Black / Magnetic Hall Effect',
        sku: 'NEX-KBD-75-BLK-HE',
        price: 199.0,
        compareAtPrice: 229.0,
        options: { Finish: 'Matte Black', SwitchType: 'Magnetic Hall Effect' },
        availableForSale: true,
        inventoryQuantity: 40,
        imageUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80',
      },
      {
        id: 'var-elec-1-3',
        title: 'Lunar White / Magnetic Hall Effect',
        sku: 'NEX-KBD-75-WHT-HE',
        price: 199.0,
        compareAtPrice: 229.0,
        options: { Finish: 'Lunar White', SwitchType: 'Magnetic Hall Effect' },
        availableForSale: true,
        inventoryQuantity: 18,
        imageUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80',
      },
    ],
    rating: { average: 4.9, count: 74 },
    specifications: {
      PollingRate: '8,000Hz (0.125ms response time)',
      ActuationRange: '0.1mm to 4.0mm (0.01mm resolution)',
      Connectivity: 'USB-C / 2.4GHz RF Low-Latency / Bluetooth 5.4',
      Chassis: 'CNC 6063 Anodized Aluminum',
      Weight: '1,350g (3.0 lbs)',
    },
    featured: true,
    createdAt: '2026-01-04T08:00:00Z',
  },
  {
    id: 'prod-elec-2',
    handle: 'flux-ultra-wireless-gaming-mouse',
    title: 'Flux Ultra Wireless Gaming Mouse',
    subtitle: '39g carbon fiber exoskeleton with 36,000 DPI optical sensor and 8K polling',
    description: 'Breakthrough weight reduction without structural flex. Powered by a carbon-composite monocoque shell, Nordic 52840 MCU, and optical microswitches rated for 100 million clicks with zero debounce delay.',
    price: 149.0,
    compareAtPrice: 169.0,
    category: 'Keyboards', // peripherals
    tags: ['keyboards', 'mouse', 'ultralight', 'carbon-fiber', 'wireless', 'bestseller'],
    images: [
      {
        id: 'img-elec-2-1',
        url: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=800&q=80',
        altText: 'Ultra-lightweight wireless optical gaming mouse resting on carbon fiber desk surface',
      },
    ],
    options: [
      { name: 'Finish', values: ['Matte Black', 'Cyber Cyan'] },
    ],
    variants: [
      {
        id: 'var-elec-2-1',
        title: 'Matte Black',
        sku: 'NEX-MOU-FLX-BLK',
        price: 149.0,
        compareAtPrice: 169.0,
        options: { Finish: 'Matte Black' },
        availableForSale: true,
        inventoryQuantity: 28,
      },
      {
        id: 'var-elec-2-2',
        title: 'Cyber Cyan',
        sku: 'NEX-MOU-FLX-CYN',
        price: 149.0,
        compareAtPrice: 169.0,
        options: { Finish: 'Cyber Cyan' },
        availableForSale: true,
        inventoryQuantity: 22,
      },
    ],
    rating: { average: 4.8, count: 62 },
    specifications: {
      Weight: '39 grams (without cable)',
      Sensor: 'PixArt PAW3395 (36,000 DPI, 650 IPS)',
      PollingRate: '8,000Hz Wireless & Wired',
      BatteryLife: '110 Hours Continuous (1000Hz mode)',
    },
    featured: true,
    createdAt: '2026-01-07T08:00:00Z',
  },
  {
    id: 'prod-elec-3',
    handle: 'low-profile-gasket-macro-keypad',
    title: 'Low-Profile Gasket Macro Keypad',
    subtitle: '9-key programmable macro pad with rotary encoder and OLED display',
    description: 'Compact programmable companion for stream automation, Blender workflow hotkeys, and IDE macros. Features hot-swappable Kailh Choc V2 switches and an interactive mini telemetry display.',
    price: 79.0,
    category: 'Keyboards',
    tags: ['keyboards', 'macropad', 'streamer', 'open-source'],
    images: [
      {
        id: 'img-elec-3-1',
        url: 'https://images.unsplash.com/photo-1595225476474-87563907a212?auto=format&fit=crop&w=800&q=80',
        altText: 'Programmable mini macro keypad with knurled metal rotary dial',
      },
    ],
    options: [
      { name: 'Finish', values: ['Matte Black', 'Silver Billet'] },
    ],
    variants: [
      {
        id: 'var-elec-3-1',
        title: 'Matte Black',
        sku: 'NEX-MAC-9K-BLK',
        price: 79.0,
        options: { Finish: 'Matte Black' },
        availableForSale: true,
        inventoryQuantity: 45,
      },
    ],
    rating: { average: 4.7, count: 31 },
    specifications: {
      Firmware: 'QMK / VIA / VIAL WebHID Supported',
      Display: '0.96-inch 128x64 Monochrome OLED',
      Encoder: 'Precision Detent Stepper Dial with Push Switch',
    },
    featured: false,
    createdAt: '2026-01-10T08:00:00Z',
  },
  {
    id: 'prod-elec-4',
    handle: 'precision-aluminum-mouse-pad',
    title: 'Precision Aluminum Mouse Pad',
    subtitle: 'Hard anodized micro-textured metal surface with non-slip silicone base',
    description: 'Engineered for speed and micro-adjustment consistency. The micro-etched sandblasted surface offers low static friction and effortless glide for high-DPI optical tracking sensors.',
    price: 49.0,
    category: 'Keyboards', // accessories
    tags: ['keyboards', 'mousepad', 'aluminum', 'accessories'],
    images: [
      {
        id: 'img-elec-4-1',
        url: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=800&q=80',
        altText: 'Sleek black anodized aluminum hard mousepad with bevelled edge',
      },
    ],
    options: [
      { name: 'Size', values: ['Medium (320x270mm)', 'Large (400x320mm)'] },
    ],
    variants: [
      {
        id: 'var-elec-4-1',
        title: 'Large (400x320mm)',
        sku: 'NEX-PAD-ALU-L',
        price: 49.0,
        options: { Size: 'Large (400x320mm)' },
        availableForSale: true,
        inventoryQuantity: 50,
      },
    ],
    rating: { average: 4.6, count: 23 },
    specifications: {
      Material: '2.5mm Anodized 5052 Aircraft Aluminum',
      Base: 'Full Coverage 1.0mm Textured Silicone',
    },
    featured: false,
    createdAt: '2026-01-12T08:00:00Z',
  },
  {
    id: 'prod-elec-5',
    handle: 'cyberpulse-wireless-anc-headphones',
    title: 'CyberPulse Wireless ANC Headphones',
    subtitle: 'Planar magnetic 50mm drivers with hybrid active noise cancellation and LDAC',
    description: 'Studio-grade acoustic resolution in an untethered form factor. Custom planar transducers deliver linear frequency response from 5Hz to 45kHz with sub-0.1% total harmonic distortion.',
    price: 299.0,
    compareAtPrice: 349.0,
    category: 'Audio',
    tags: ['audio', 'headphones', 'planar-magnetic', 'anc', 'lossless', 'bestseller'],
    images: [
      {
        id: 'img-elec-5-1',
        url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
        altText: 'Premium matte black over-ear planar magnetic headphones with cyan accent ring',
      },
    ],
    options: [
      { name: 'Finish', values: ['Matte Black', 'Cyber Cyan', 'Lunar White'] },
    ],
    variants: [
      {
        id: 'var-elec-5-1',
        title: 'Matte Black',
        sku: 'NEX-AUD-CYB-BLK',
        price: 299.0,
        compareAtPrice: 349.0,
        options: { Finish: 'Matte Black' },
        availableForSale: true,
        inventoryQuantity: 24,
      },
      {
        id: 'var-elec-5-2',
        title: 'Cyber Cyan',
        sku: 'NEX-AUD-CYB-CYN',
        price: 299.0,
        compareAtPrice: 349.0,
        options: { Finish: 'Cyber Cyan' },
        availableForSale: true,
        inventoryQuantity: 16,
      },
    ],
    rating: { average: 4.9, count: 58 },
    specifications: {
      DriverType: '50mm Planar Magnetic with Neodymium N52 Magnets',
      FrequencyResponse: '5Hz - 45,000Hz (Hi-Res Certified)',
      CodecsSupported: 'LDAC, aptX Adaptive, AAC, SBC, USB-C 24-bit/96kHz',
      NoiseCancellation: '4-Mic Hybrid ANC (-42dB attenuation)',
      BatteryLife: '55 Hours (ANC On) / 70 Hours (ANC Off)',
    },
    featured: true,
    createdAt: '2026-01-15T08:00:00Z',
  },
  {
    id: 'prod-elec-6',
    handle: 'acoustic-studio-desk-speakers',
    title: 'Acoustic Studio Desk Speakers',
    subtitle: 'Bi-amplified nearfield active monitors with beryllium tweeters and DSP room correction',
    description: 'Reference audio precision designed for creators and mixing engineers. Features dual 65W Class-D amplifiers per speaker, 4-inch woven Kevlar mid-woofers, and integrated optical/USB-C inputs.',
    price: 380.0,
    compareAtPrice: 420.0,
    category: 'Audio',
    tags: ['audio', 'monitors', 'speakers', 'studio'],
    images: [
      {
        id: 'img-elec-6-1',
        url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
        altText: 'Pair of compact high-end studio reference desk speakers with yellow kevlar cones',
      },
    ],
    options: [
      { name: 'Finish', values: ['Matte Black', 'Brushed Aluminum'] },
    ],
    variants: [
      {
        id: 'var-elec-6-1',
        title: 'Matte Black',
        sku: 'NEX-SPK-STU-BLK',
        price: 380.0,
        compareAtPrice: 420.0,
        options: { Finish: 'Matte Black' },
        availableForSale: true,
        inventoryQuantity: 14,
      },
    ],
    rating: { average: 4.8, count: 37 },
    specifications: {
      OutputPower: '130W Total Peak Output (Bi-Amped)',
      FrequencyRange: '45Hz - 28kHz (±2dB)',
      Inputs: 'Balanced TRS, RCA, USB-C 32-bit DAC, Optical Toslink',
    },
    featured: true,
    createdAt: '2026-01-18T08:00:00Z',
  },
  {
    id: 'prod-elec-7',
    handle: 'lossless-bluetooth-wireless-iems',
    title: 'Lossless Bluetooth Wireless IEMs',
    subtitle: 'Dual-driver hybrid in-ear monitors with Knowles balanced armatures and aptX Lossless',
    description: 'Compact audiophile fidelity. Houses a 10mm graphene dynamic driver for visceral sub-bass paired with twin Knowles armatures for sparkling highs, housed inside 3D-printed biocompatible resin.',
    price: 189.0,
    category: 'Audio',
    tags: ['audio', 'iem', 'earbuds', 'wireless', 'lossless'],
    images: [
      {
        id: 'img-elec-7-1',
        url: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80',
        altText: 'Translucent resin wireless in-ear monitors resting in aluminum charging case',
      },
    ],
    options: [
      { name: 'Finish', values: ['Smoky Obsidian', 'Cyber Cyan'] },
    ],
    variants: [
      {
        id: 'var-elec-7-1',
        title: 'Cyber Cyan',
        sku: 'NEX-IEM-WRL-CYN',
        price: 189.0,
        options: { Finish: 'Cyber Cyan' },
        availableForSale: true,
        inventoryQuantity: 30,
      },
    ],
    rating: { average: 4.8, count: 45 },
    specifications: {
      DriverSetup: '1x 10mm Graphene Dynamic + 2x Knowles BA',
      WaterResistance: 'IPX5 Sweat Resistance',
      TotalPlayback: '38 Hours with Case',
    },
    featured: false,
    createdAt: '2026-01-20T08:00:00Z',
  },
  {
    id: 'prod-elec-8',
    handle: 'broadcast-cardioid-xlr-microphone',
    title: 'Broadcast Cardioid XLR Microphone',
    subtitle: 'Large diaphragm dynamic broadcast mic with internal pneumatic shock mount',
    description: 'Radio-ready vocal presence with profound off-axis rejection. Custom tuned capsule captures warm, rich low-end proximity effect while rejecting ambient mechanical keyboard clatter.',
    price: 219.0,
    compareAtPrice: 249.0,
    category: 'Audio',
    tags: ['audio', 'microphone', 'xlr', 'broadcast', 'streaming'],
    images: [
      {
        id: 'img-elec-8-1',
        url: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80',
        altText: 'Matte black dynamic broadcast microphone mounted on articulated studio boom arm',
      },
    ],
    options: [
      { name: 'Finish', values: ['Matte Black'] },
    ],
    variants: [
      {
        id: 'var-elec-8-1',
        title: 'Matte Black',
        sku: 'NEX-MIC-XLR-BLK',
        price: 219.0,
        compareAtPrice: 249.0,
        options: { Finish: 'Matte Black' },
        availableForSale: true,
        inventoryQuantity: 21,
      },
    ],
    rating: { average: 4.9, count: 50 },
    specifications: {
      CapsuleType: 'Custom Dynamic Moving Coil',
      PolarPattern: 'Supercardioid Tight Isolation',
      Connector: 'Gold-Plated 3-Pin XLR',
    },
    featured: false,
    createdAt: '2026-01-22T08:00:00Z',
  },
  {
    id: 'prod-elec-9',
    handle: 'quantumview-27-240hz-oled-monitor',
    title: 'QuantumView 27" 240Hz OLED Monitor',
    subtitle: 'QHD 2560x1440 3rd-Gen QD-OLED panel with 0.03ms response time and 99% DCI-P3',
    description: 'The holy grail of esports clarity and HDR depth. Self-lit pixels deliver infinite contrast ratio, certified True Black 400, AMD FreeSync Premium Pro, and custom graphene passive heatsink cooling.',
    price: 799.0,
    compareAtPrice: 899.0,
    category: 'Displays',
    tags: ['displays', 'oled', '240hz', 'gaming', 'hdr', 'bestseller'],
    images: [
      {
        id: 'img-elec-9-1',
        url: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=800&q=80',
        altText: 'Ultra thin bezel 27 inch OLED gaming monitor displaying vibrant neon test pattern',
      },
    ],
    options: [
      { name: 'Finish', values: ['Cyber Cyan Accent', 'Stealth Black'] },
    ],
    variants: [
      {
        id: 'var-elec-9-1',
        title: 'Cyber Cyan Accent',
        sku: 'NEX-DSP-27OLED-CYN',
        price: 799.0,
        compareAtPrice: 899.0,
        options: { Finish: 'Cyber Cyan Accent' },
        availableForSale: true,
        inventoryQuantity: 15,
      },
    ],
    rating: { average: 5.0, count: 68 },
    specifications: {
      PanelTechnology: '27-inch Quantum Dot OLED',
      Resolution: '2560 x 1440 (QHD 16:9)',
      RefreshRate: '240Hz Native (0.03ms GtG Response)',
      ColorAccuracy: 'Delta E < 1.0 Factory Calibrated, 99.3% DCI-P3',
      Connectivity: 'DisplayPort 2.1, 2x HDMI 2.1, USB-C 90W PD',
    },
    featured: true,
    createdAt: '2026-01-25T08:00:00Z',
  },
  {
    id: 'prod-elec-10',
    handle: 'ultra-wide-curved-49-display',
    title: 'Ultra-Wide Curved 49" Display',
    subtitle: 'Dual QHD 5120x1440 1800R curved panoramic productivity monitor with KVM switch',
    description: 'Equivalent to two seamless 27-inch monitors side by side. Features an integrated hardware KVM switch to control two computers with a single keyboard and mouse, plus multi-source PiP/PbP.',
    price: 1199.0,
    category: 'Displays',
    tags: ['displays', 'ultrawide', 'curved', 'workstation'],
    images: [
      {
        id: 'img-elec-10-1',
        url: 'https://images.unsplash.com/photo-1547082299-de196ea013d6?auto=format&fit=crop&w=800&q=80',
        altText: 'Expansive 49 inch curved ultrawide workstation display on floating desk arm',
      },
    ],
    options: [
      { name: 'Finish', values: ['Stealth Black'] },
    ],
    variants: [
      {
        id: 'var-elec-10-1',
        title: 'Stealth Black',
        sku: 'NEX-DSP-49CRV-BLK',
        price: 1199.0,
        options: { Finish: 'Stealth Black' },
        availableForSale: true,
        inventoryQuantity: 8,
      },
    ],
    rating: { average: 4.8, count: 29 },
    specifications: {
      AspectCurve: '32:9 Super Ultra-Wide, 1800R Curvature',
      Resolution: '5120 x 1440 (Dual QHD)',
      Features: 'Built-in KVM Switch, 90W USB-C Single-Cable Docking',
    },
    featured: false,
    createdAt: '2026-01-28T08:00:00Z',
  },
  {
    id: 'prod-elec-11',
    handle: 'ultra-thin-4k-portable-creator-oled',
    title: 'Ultra-Thin 4K Portable Creator OLED',
    subtitle: '15.6" UHD 3840x2160 100% Adobe RGB portable OLED with capacitive touch & stylus',
    description: 'Color-critical studio grading in an ultra-slim 550g magnesium chassis. Powered directly over a single USB-C cable from your laptop, camera, or iPad Pro for on-location field production.',
    price: 449.0,
    compareAtPrice: 499.0,
    category: 'Displays',
    tags: ['displays', 'portable', '4k', 'oled', 'touchscreen'],
    images: [
      {
        id: 'img-elec-11-1',
        url: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=800&q=80',
        altText: 'Slim portable 4K OLED monitor standing beside laptop displaying photo grading tool',
      },
    ],
    options: [
      { name: 'Finish', values: ['Space Grey'] },
    ],
    variants: [
      {
        id: 'var-elec-11-1',
        title: 'Space Grey',
        sku: 'NEX-DSP-15PRT-GRY',
        price: 449.0,
        compareAtPrice: 499.0,
        options: { Finish: 'Space Grey' },
        availableForSale: true,
        inventoryQuantity: 20,
      },
    ],
    rating: { average: 4.9, count: 36 },
    specifications: {
      DisplaySize: '15.6 inch 4K OLED (3840 x 2160)',
      PeakBrightness: '550 nits HDR Peak',
      ThicknessWeight: '4.8mm Slim Profile, 550g Total',
    },
    featured: false,
    createdAt: '2026-01-30T08:00:00Z',
  },
  {
    id: 'prod-elec-12',
    handle: 'titanium-ergonomic-monitor-arm',
    title: 'Titanium Ergonomic Monitor Arm',
    subtitle: 'Gas-spring mechanical arm supporting heavy displays up to 49" and 20kg',
    description: 'Effortless fingertip repositioning with internal gas-strut counterbalance. Concealed pass-through cable management channels keep power and video cables entirely out of view.',
    price: 129.0,
    category: 'Displays', // accessories
    tags: ['displays', 'monitor-arm', 'ergonomic', 'accessories'],
    images: [
      {
        id: 'img-elec-12-1',
        url: 'https://images.unsplash.com/photo-1547082299-de196ea013d6?auto=format&fit=crop&w=800&q=80',
        altText: 'Heavy-duty matte black gas spring monitor arm supporting large screen',
      },
    ],
    options: [
      { name: 'Finish', values: ['Matte Black', 'Brushed Titanium'] },
    ],
    variants: [
      {
        id: 'var-elec-12-1',
        title: 'Matte Black',
        sku: 'NEX-ARM-MNT-BLK',
        price: 129.0,
        options: { Finish: 'Matte Black' },
        availableForSale: true,
        inventoryQuantity: 35,
      },
    ],
    rating: { average: 4.8, count: 42 },
    specifications: {
      WeightCapacity: 'Up to 20kg (44 lbs)',
      Compatibility: 'VESA 75x75 & 100x100',
      Range: '360° Rotation, +90°/-15° Tilt, 540mm Reach',
    },
    featured: false,
    createdAt: '2026-02-01T08:00:00Z',
  },
  {
    id: 'prod-elec-13',
    handle: 'thunderbolt-5-dual-8k-modular-dock',
    title: 'Thunderbolt 5 Dual 8K Modular Dock',
    subtitle: '120Gbps bandwidth hub with 140W host charging and 2.5GbE Ethernet',
    description: 'The definitive single-cable docking station. Drives two 8K 60Hz displays or three 4K 144Hz panels simultaneously while charging power-hungry workstation laptops at up to 140 watts.',
    price: 329.0,
    compareAtPrice: 369.0,
    category: 'Components',
    tags: ['components', 'dock', 'thunderbolt', 'fast-charging', 'bestseller'],
    images: [
      {
        id: 'img-elec-13-1',
        url: 'https://images.unsplash.com/photo-1544652478-6653e09f18a2?auto=format&fit=crop&w=800&q=80',
        altText: 'Sleek aluminum Thunderbolt desktop dock with array of high speed ports',
      },
    ],
    options: [
      { name: 'Finish', values: ['Space Grey Aluminum'] },
    ],
    variants: [
      {
        id: 'var-elec-13-1',
        title: 'Space Grey Aluminum',
        sku: 'NEX-DCK-TB5-GRY',
        price: 329.0,
        compareAtPrice: 369.0,
        options: { Finish: 'Space Grey Aluminum' },
        availableForSale: true,
        inventoryQuantity: 18,
      },
    ],
    rating: { average: 4.9, count: 54 },
    specifications: {
      Standard: 'Thunderbolt 5 (120Gbps Bandwidth Boost)',
      HostCharging: '140W USB Power Delivery 3.1 EPR',
      PortSelection: '3x TB5, 4x USB-A 10Gbps, 2.5G Ethernet, SD 4.0 UHS-II, 3.5mm Combo',
    },
    featured: false,
    createdAt: '2026-02-03T08:00:00Z',
  },
  {
    id: 'prod-elec-14',
    handle: 'nvme-gen5-extreme-solid-state-drive',
    title: 'NVMe Gen5 Extreme Solid State Drive',
    subtitle: 'PCIe 5.0 x4 M.2 SSD with active fan-cooled vapor chamber heatsink',
    description: 'Blistering sequential speeds of 14,500 MB/s read and 12,500 MB/s write. Eliminates game load screens and ingests uncompressed 8K RAW video footage with zero thermal throttling.',
    price: 249.0,
    category: 'Components',
    tags: ['components', 'ssd', 'nvme', 'gen5', 'high-speed'],
    images: [
      {
        id: 'img-elec-14-1',
        url: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?auto=format&fit=crop&w=800&q=80',
        altText: 'M.2 PCIe Gen5 solid state drive with black ribbed heatsink and copper heat pipes',
      },
    ],
    options: [
      { name: 'Storage', values: ['2TB', '4TB'] },
    ],
    variants: [
      {
        id: 'var-elec-14-1',
        title: '2TB',
        sku: 'NEX-SSD-GEN5-2TB',
        price: 249.0,
        options: { Storage: '2TB' },
        availableForSale: true,
        inventoryQuantity: 25,
      },
      {
        id: 'var-elec-14-2',
        title: '4TB',
        sku: 'NEX-SSD-GEN5-4TB',
        price: 439.0,
        options: { Storage: '4TB' },
        availableForSale: true,
        inventoryQuantity: 14,
      },
    ],
    rating: { average: 4.8, count: 39 },
    specifications: {
      SequentialRead: 'Up to 14,500 MB/s',
      SequentialWrite: 'Up to 12,500 MB/s',
      Endurance: '3,000 TBW (Terabytes Written for 4TB)',
      Controller: 'Phison PS5026-E26 12nm Controller',
    },
    featured: false,
    createdAt: '2026-02-05T08:00:00Z',
  },
  {
    id: 'prod-elec-15',
    handle: 'aerostream-high-flow-desktop-chassis',
    title: 'AeroStream High-Flow Desktop Chassis',
    subtitle: 'ATX dual-chamber computer case with panoramic curved tempered glass and 5x fans',
    description: 'Designed for peak component thermal efficiency. Dual chamber layout keeps the power supply and cabling separate from graphics cards and CPU cooling radiators, featuring high-flow mesh intake.',
    price: 189.0,
    compareAtPrice: 219.0,
    category: 'Components',
    tags: ['components', 'pc-case', 'chassis', 'gaming', 'cooling'],
    images: [
      {
        id: 'img-elec-15-1',
        url: 'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=800&q=80',
        altText: 'Panoramic tempered glass gaming computer chassis with internal cyan lighting',
      },
    ],
    options: [
      { name: 'Finish', values: ['Matte Black', 'Lunar White'] },
    ],
    variants: [
      {
        id: 'var-elec-15-1',
        title: 'Matte Black',
        sku: 'NEX-CHS-AER-BLK',
        price: 189.0,
        compareAtPrice: 219.0,
        options: { Finish: 'Matte Black' },
        availableForSale: true,
        inventoryQuantity: 16,
      },
    ],
    rating: { average: 4.9, count: 48 },
    specifications: {
      FormFactor: 'Mid-Tower Dual Chamber ATX',
      RadiatorSupport: 'Up to Dual 360mm Top & Side Radiators',
      IncludedFans: '5x 120mm PWM Low-Noise ARGB Fans',
    },
    featured: false,
    createdAt: '2026-02-07T08:00:00Z',
  },
  {
    id: 'prod-elec-16',
    handle: 'omnicharge-140w-gan-fast-charger',
    title: 'OmniCharge 140W GaN Fast Charger',
    subtitle: 'Ultra-compact Gallium Nitride 3x USB-C + 1x USB-A multi-device wall adapter',
    description: 'Replace four bulky power bricks with one pocket-sized adapter. Dynamically allocates up to 140W across connected laptops, phones, and accessories with zero power drop during re-plugging.',
    price: 89.0,
    compareAtPrice: 105.0,
    category: 'Components', // accessories
    tags: ['components', 'charger', 'gan', 'fast-charging', 'travel'],
    images: [
      {
        id: 'img-elec-16-1',
        url: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=800&q=80',
        altText: 'Compact black GaN multi-port wall charger resting next to braided USB-C cable',
      },
    ],
    options: [
      { name: 'Finish', values: ['Matte Black', 'Lunar White'] },
    ],
    variants: [
      {
        id: 'var-elec-16-1',
        title: 'Matte Black',
        sku: 'NEX-CHG-140-BLK',
        price: 89.0,
        compareAtPrice: 105.0,
        options: { Finish: 'Matte Black' },
        availableForSale: true,
        inventoryQuantity: 42,
      },
    ],
    rating: { average: 4.8, count: 57 },
    specifications: {
      Technology: 'Navitas GaNFast Power ICs',
      OutputPorts: '3x USB-C (PD 3.1 EPR 140W Max), 1x USB-A (22.5W Max)',
      Dimensions: '75mm x 60mm x 32mm (40% smaller than OEM chargers)',
    },
    featured: false,
    createdAt: '2026-02-09T08:00:00Z',
  },
];

export default electronicsProducts;
