import { Product } from '../../types/product';

export const fashionProducts: Product[] = [
  {
    id: 'prod-fashion-1',
    handle: 'oversized-double-breasted-wool-coat',
    title: 'Oversized Double-Breasted Wool Coat',
    subtitle: 'Heavyweight Italian virgin wool with dropped shoulders and Horn buttons',
    description: 'An imposing, architectural silhouette cut from 850gsm virgin wool woven in Biella, Italy. Features wide peaked lapels, deep welt pockets, a satin-cupro lining, and a dramatic back vent.',
    price: 495.0,
    compareAtPrice: 580.0,
    category: 'Outerwear',
    tags: ['outerwear', 'wool', 'winter', 'runway', 'bestseller'],
    images: [
      {
        id: 'img-fashion-1-1',
        url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=800&q=80',
        altText: 'Full length view of oversized black double-breasted wool overcoat on model',
      },
      {
        id: 'img-fashion-1-2',
        url: 'https://images.unsplash.com/photo-1544022613-e87ca75a784a?auto=format&fit=crop&w=800&q=80',
        altText: 'Detail shot of wide peak lapel and genuine buffalo horn buttons on wool coat',
      },
    ],
    options: [
      { name: 'Size', values: ['XS', 'S', 'M', 'L', 'XL'] },
      { name: 'Color', values: ['Onyx Black', 'Charcoal Heather'] },
    ],
    variants: [
      {
        id: 'var-fashion-1-1',
        title: 'XS / Onyx Black',
        sku: 'FAS-COAT-XS-BLK',
        price: 495.0,
        compareAtPrice: 580.0,
        options: { Size: 'XS', Color: 'Onyx Black' },
        availableForSale: true,
        inventoryQuantity: 8,
      },
      {
        id: 'var-fashion-1-2',
        title: 'S / Onyx Black',
        sku: 'FAS-COAT-S-BLK',
        price: 495.0,
        compareAtPrice: 580.0,
        options: { Size: 'S', Color: 'Onyx Black' },
        availableForSale: true,
        inventoryQuantity: 14,
      },
      {
        id: 'var-fashion-1-3',
        title: 'M / Onyx Black',
        sku: 'FAS-COAT-M-BLK',
        price: 495.0,
        compareAtPrice: 580.0,
        options: { Size: 'M', Color: 'Onyx Black' },
        availableForSale: true,
        inventoryQuantity: 20,
      },
      {
        id: 'var-fashion-1-4',
        title: 'L / Onyx Black',
        sku: 'FAS-COAT-L-BLK',
        price: 495.0,
        compareAtPrice: 580.0,
        options: { Size: 'L', Color: 'Onyx Black' },
        availableForSale: true,
        inventoryQuantity: 10,
      },
      {
        id: 'var-fashion-1-5',
        title: 'M / Charcoal Heather',
        sku: 'FAS-COAT-M-CHR',
        price: 495.0,
        compareAtPrice: 580.0,
        options: { Size: 'M', Color: 'Charcoal Heather' },
        availableForSale: true,
        inventoryQuantity: 7,
      },
    ],
    rating: { average: 4.9, count: 42 },
    specifications: {
      Material: '100% Virgin Wool (850gsm)',
      Lining: '100% Bemberg Cupro',
      Origin: 'Crafted in Milan, Italy',
      Fit: 'Generous Relaxed Silhouette',
      Care: 'Dry Clean Only by Specialist',
    },
    featured: true,
    createdAt: '2026-01-08T08:00:00Z',
  },
  {
    id: 'prod-fashion-2',
    handle: 'structured-gabardine-trench-coat',
    title: 'Structured Gabardine Trench Coat',
    subtitle: 'Water-repellent bonded cotton gabardine with removable storm flap',
    description: 'A contemporary rethinking of military trenching. Crisp structured cotton treated with an eco-certified water-shedding finish. Features a storm flap, gun patch, and a wide buckled waist belt.',
    price: 420.0,
    category: 'Outerwear',
    tags: ['outerwear', 'cotton', 'trench', 'minimalist'],
    images: [
      {
        id: 'img-fashion-2-1',
        url: 'https://images.unsplash.com/photo-1548883354-7622d03aca27?auto=format&fit=crop&w=800&q=80',
        altText: 'Model in architectural belted gabardine trench coat with storm collar turned up',
      },
    ],
    options: [
      { name: 'Size', values: ['S', 'M', 'L'] },
      { name: 'Color', values: ['Onyx Black', 'Bone White'] },
    ],
    variants: [
      {
        id: 'var-fashion-2-1',
        title: 'S / Onyx Black',
        sku: 'FAS-TRN-S-BLK',
        price: 420.0,
        options: { Size: 'S', Color: 'Onyx Black' },
        availableForSale: true,
        inventoryQuantity: 12,
      },
      {
        id: 'var-fashion-2-2',
        title: 'M / Onyx Black',
        sku: 'FAS-TRN-M-BLK',
        price: 420.0,
        options: { Size: 'M', Color: 'Onyx Black' },
        availableForSale: true,
        inventoryQuantity: 18,
      },
    ],
    rating: { average: 4.8, count: 29 },
    specifications: {
      Material: '100% Compact Cotton Gabardine',
      Origin: 'Crafted in Porto, Portugal',
      WaterResistance: 'DWR Repellent Finish',
    },
    featured: true,
    createdAt: '2026-01-10T08:00:00Z',
  },
  {
    id: 'prod-fashion-3',
    handle: 'technical-nylon-storm-parka',
    title: 'Technical Nylon Storm Parka',
    subtitle: '3-layer membrane waterproof ripstop with taped waterproof seams',
    description: 'Minimal utilitarian protection against harsh elements. Fully taped inner seams, waterproof YKK Aquaguard zippers, and a stowaway peaked storm hood combine technical utility with clean lines.',
    price: 360.0,
    compareAtPrice: 410.0,
    category: 'Outerwear',
    tags: ['outerwear', 'technical', 'rainwear', 'waterproof'],
    images: [
      {
        id: 'img-fashion-3-1',
        url: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=800&q=80',
        altText: 'Technical hooded black storm parka featuring matte waterproof finish',
      },
    ],
    options: [
      { name: 'Size', values: ['S', 'M', 'L', 'XL'] },
      { name: 'Color', values: ['Onyx Black', 'Charcoal Heather'] },
    ],
    variants: [
      {
        id: 'var-fashion-3-1',
        title: 'M / Onyx Black',
        sku: 'FAS-PRK-M-BLK',
        price: 360.0,
        compareAtPrice: 410.0,
        options: { Size: 'M', Color: 'Onyx Black' },
        availableForSale: true,
        inventoryQuantity: 15,
      },
    ],
    rating: { average: 4.7, count: 21 },
    specifications: {
      Material: '3-Layer Recycled Polyamide Ripstop',
      Breathability: '20,000 g/m²/24h',
      WaterColumn: '25,000mm',
    },
    featured: false,
    createdAt: '2026-01-12T08:00:00Z',
  },
  {
    id: 'prod-fashion-4',
    handle: 'cropped-structured-wool-bomber',
    title: 'Cropped Structured Wool Bomber',
    subtitle: 'Heavy melton wool body with ribbed wool trims and two-way nickel zipper',
    description: 'A sharp, modern silhouette sitting right at the natural waist. Substantial double-faced wool keeps its clean boxy shape without sagging, finished with matte gunmetal hardware.',
    price: 310.0,
    category: 'Outerwear',
    tags: ['outerwear', 'bomber', 'wool', 'cropped'],
    images: [
      {
        id: 'img-fashion-4-1',
        url: 'https://images.unsplash.com/photo-1544923246-77307dd654cb?auto=format&fit=crop&w=800&q=80',
        altText: 'Cropped minimalist black wool bomber jacket on hanger against concrete wall',
      },
    ],
    options: [
      { name: 'Size', values: ['XS', 'S', 'M', 'L'] },
      { name: 'Color', values: ['Onyx Black'] },
    ],
    variants: [
      {
        id: 'var-fashion-4-1',
        title: 'S / Onyx Black',
        sku: 'FAS-BMB-S-BLK',
        price: 310.0,
        options: { Size: 'S', Color: 'Onyx Black' },
        availableForSale: true,
        inventoryQuantity: 16,
      },
    ],
    rating: { average: 4.8, count: 34 },
    specifications: {
      Material: '100% Melton Wool (600gsm)',
      Origin: 'Crafted in Japan',
      Hardware: 'YKK Excella Two-Way Metal Zipper',
    },
    featured: false,
    createdAt: '2026-01-14T08:00:00Z',
  },
  {
    id: 'prod-fashion-5',
    handle: 'deconstructed-architecture-blazer',
    title: 'Deconstructed Architecture Blazer',
    subtitle: 'Single-breasted fluid wool blazer with soft shoulder and floating canvas',
    description: 'Liberating tailoring from rigid constraint. Handcrafted with an unpadded floating chest canvas that molds naturally to the body, clean jet pockets, and raw-edge seam detailing.',
    price: 380.0,
    compareAtPrice: 440.0,
    category: 'Tailoring',
    tags: ['tailoring', 'blazer', 'wool', 'essential', 'bestseller'],
    images: [
      {
        id: 'img-fashion-5-1',
        url: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&q=80',
        altText: 'Model in deconstructed black fluid wool single-breasted blazer with relaxed stance',
      },
    ],
    options: [
      { name: 'Size', values: ['36R', '38R', '40R', '42R'] },
      { name: 'Color', values: ['Onyx Black', 'Charcoal Heather'] },
    ],
    variants: [
      {
        id: 'var-fashion-5-1',
        title: '38R / Onyx Black',
        sku: 'FAS-BLZ-38-BLK',
        price: 380.0,
        compareAtPrice: 440.0,
        options: { Size: '38R', Color: 'Onyx Black' },
        availableForSale: true,
        inventoryQuantity: 12,
      },
      {
        id: 'var-fashion-5-2',
        title: '40R / Onyx Black',
        sku: 'FAS-BLZ-40-BLK',
        price: 380.0,
        compareAtPrice: 440.0,
        options: { Size: '40R', Color: 'Onyx Black' },
        availableForSale: true,
        inventoryQuantity: 18,
      },
    ],
    rating: { average: 4.9, count: 56 },
    specifications: {
      Material: '100% Super 120s High-Twist Wool',
      Canvas: 'Half-Canvas Floating Chest Piece',
      Origin: 'Crafted in Naples, Italy',
    },
    featured: true,
    createdAt: '2026-01-16T08:00:00Z',
  },
  {
    id: 'prod-fashion-6',
    handle: 'wide-leg-pleated-wool-trousers',
    title: 'Wide-Leg Pleated Wool Trousers',
    subtitle: 'High-rise forward double pleat trousers with fluid draping leg',
    description: 'An expansive silhouette that pools effortlessly over footwear. Deep front pleats generate clean volume from the high-set waistband down to the wide 24cm hem opening.',
    price: 240.0,
    category: 'Tailoring',
    tags: ['tailoring', 'trousers', 'pleated', 'wide-leg'],
    images: [
      {
        id: 'img-fashion-6-1',
        url: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=800&q=80',
        altText: 'Wide-leg black wool pleated trousers styled with minimalist footwear',
      },
    ],
    options: [
      { name: 'Size', values: ['28', '30', '32', '34'] },
      { name: 'Color', values: ['Onyx Black', 'Bone White'] },
    ],
    variants: [
      {
        id: 'var-fashion-6-1',
        title: '30 / Onyx Black',
        sku: 'FAS-TRS-30-BLK',
        price: 240.0,
        options: { Size: '30', Color: 'Onyx Black' },
        availableForSale: true,
        inventoryQuantity: 20,
      },
      {
        id: 'var-fashion-6-2',
        title: '32 / Onyx Black',
        sku: 'FAS-TRS-32-BLK',
        price: 240.0,
        options: { Size: '32', Color: 'Onyx Black' },
        availableForSale: true,
        inventoryQuantity: 24,
      },
    ],
    rating: { average: 4.8, count: 48 },
    specifications: {
      Material: '100% Tropical Wool Worsted',
      Waistband: 'Extended Tab with Concealed Hook Closure',
      Inseam: 'Unfinished 36-inch for Bespoke Hemming',
    },
    featured: true,
    createdAt: '2026-01-18T08:00:00Z',
  },
  {
    id: 'prod-fashion-7',
    handle: 'japanese-selvedge-denim-jean',
    title: 'Japanese Selvedge Denim Jean',
    subtitle: '14oz Kurabo shuttle loom denim with silver selvedge ID line',
    description: 'Woven slowly on vintage Toyoda shuttle looms in Okayama. Untreated, unwashed raw denim that breaks in over years to mirror the unique movement patterns of the wearer.',
    price: 220.0,
    category: 'Tailoring',
    tags: ['tailoring', 'denim', 'selvedge', 'japan', 'raw'],
    images: [
      {
        id: 'img-fashion-7-1',
        url: 'https://images.unsplash.com/photo-1542272604-780c96856592?auto=format&fit=crop&w=800&q=80',
        altText: 'Cuffed raw indigo and black selvedge denim jeans showing selvedge ticker',
      },
    ],
    options: [
      { name: 'Size', values: ['29', '30', '31', '32', '34'] },
      { name: 'Wash', values: ['Raw Solid Black', 'Deep Indigo'] },
    ],
    variants: [
      {
        id: 'var-fashion-7-1',
        title: '32 / Raw Solid Black',
        sku: 'FAS-JNS-32-BLK',
        price: 220.0,
        options: { Size: '32', Wash: 'Raw Solid Black' },
        availableForSale: true,
        inventoryQuantity: 19,
      },
    ],
    rating: { average: 4.9, count: 37 },
    specifications: {
      Fabric: '14oz Kurabo Japanese Selvedge',
      Rivets: 'Hidden Solid Copper Rivets',
      Origin: 'Kojima, Okayama, Japan',
    },
    featured: false,
    createdAt: '2026-01-20T08:00:00Z',
  },
  {
    id: 'prod-fashion-8',
    handle: 'raw-silk-minimalist-drape-shirt',
    title: 'Raw Silk Minimalist Drape Shirt',
    subtitle: 'Noil silk slub texture with concealed placket and point collar',
    description: 'The natural character of raw noil silk gives this button-up a tactile, matte hand and exceptional breathability. Cut with a relaxed box pleat back and clean mother-of-pearl buttons.',
    price: 190.0,
    compareAtPrice: 225.0,
    category: 'Tailoring',
    tags: ['tailoring', 'shirt', 'silk', 'summer', 'minimalist'],
    images: [
      {
        id: 'img-fashion-8-1',
        url: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=800&q=80',
        altText: 'Off-white raw silk shirt with fluid collar drape and mother-of-pearl buttons',
      },
    ],
    options: [
      { name: 'Size', values: ['S', 'M', 'L'] },
      { name: 'Color', values: ['Bone White', 'Onyx Black'] },
    ],
    variants: [
      {
        id: 'var-fashion-8-1',
        title: 'M / Bone White',
        sku: 'FAS-SHT-M-WHT',
        price: 190.0,
        compareAtPrice: 225.0,
        options: { Size: 'M', Color: 'Bone White' },
        availableForSale: true,
        inventoryQuantity: 22,
      },
    ],
    rating: { average: 4.7, count: 26 },
    specifications: {
      Material: '100% Silk Noil (Raw Silk)',
      Buttons: 'Genuine Australian Mother of Pearl',
      Care: 'Hand Wash Cold or Dry Clean',
    },
    featured: false,
    createdAt: '2026-01-22T08:00:00Z',
  },
  {
    id: 'prod-fashion-9',
    handle: 'heavyweight-merino-ribbed-turtleneck',
    title: 'Heavyweight Merino Ribbed Turtleneck',
    subtitle: '5-gauge chunky cardigan rib knit with foldover seamless neck',
    description: 'Substantial, architectural knitwear. Spun from 19.5 micron Australian extra-fine merino wool, this chunky ribbed turtleneck traps insulating heat while retaining its crisp sculptural collar shape.',
    price: 260.0,
    category: 'Knitwear',
    tags: ['knitwear', 'merino', 'turtleneck', 'winter', 'warm'],
    images: [
      {
        id: 'img-fashion-9-1',
        url: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=800&q=80',
        altText: 'Close-up of heavy ribbed black merino wool turtleneck knit on model',
      },
    ],
    options: [
      { name: 'Size', values: ['S', 'M', 'L', 'XL'] },
      { name: 'Color', values: ['Onyx Black', 'Camel'] },
    ],
    variants: [
      {
        id: 'var-fashion-9-1',
        title: 'M / Onyx Black',
        sku: 'FAS-KNT-M-BLK',
        price: 260.0,
        options: { Size: 'M', Color: 'Onyx Black' },
        availableForSale: true,
        inventoryQuantity: 28,
      },
    ],
    rating: { average: 4.8, count: 39 },
    specifications: {
      Yarn: '100% Extra-Fine Merino Wool (5-Gauge)',
      KnitStructure: 'English Rib Knit',
      Origin: 'Knitted in Scotland',
    },
    featured: false,
    createdAt: '2026-01-24T08:00:00Z',
  },
  {
    id: 'prod-fashion-10',
    handle: 'seamless-cashmere-crewneck',
    title: 'Seamless Cashmere Crewneck',
    subtitle: 'WholeGarment 3D knitted 2-ply Mongolian cashmere sweater',
    description: 'Knitted as a singular three-dimensional garment without side seams or shoulder stitches. Zero friction points against the body, offering featherweight warmth and cloud-like softness.',
    price: 340.0,
    compareAtPrice: 395.0,
    category: 'Knitwear',
    tags: ['knitwear', 'cashmere', 'luxury', 'seamless'],
    images: [
      {
        id: 'img-fashion-10-1',
        url: 'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?auto=format&fit=crop&w=800&q=80',
        altText: 'Folded luxury cashmere knit sweaters in monochrome color palette',
      },
    ],
    options: [
      { name: 'Size', values: ['XS', 'S', 'M', 'L'] },
      { name: 'Color', values: ['Charcoal Heather', 'Bone White'] },
    ],
    variants: [
      {
        id: 'var-fashion-10-1',
        title: 'M / Charcoal Heather',
        sku: 'FAS-CSH-M-CHR',
        price: 340.0,
        compareAtPrice: 395.0,
        options: { Size: 'M', Color: 'Charcoal Heather' },
        availableForSale: true,
        inventoryQuantity: 15,
      },
    ],
    rating: { average: 5.0, count: 31 },
    specifications: {
      Material: '100% Grade-A Mongolian Cashmere',
      Technology: 'Shima Seiki 3D WholeGarment',
      FiberLength: '36mm Long-Staple Fibers',
    },
    featured: false,
    createdAt: '2026-01-26T08:00:00Z',
  },
  {
    id: 'prod-fashion-11',
    handle: 'brushed-mohair-cardigan',
    title: 'Brushed Mohair Cardigan',
    subtitle: 'Fluffy brushed South African kid mohair with genuine horn buttons',
    description: 'Hazy texture meets modern proportion. Hand-brushed with natural thistle burs to lift delicate fibers into a soft tactile halo. Drop shoulders and deep ribbed cuffs.',
    price: 290.0,
    category: 'Knitwear',
    tags: ['knitwear', 'mohair', 'cardigan', 'texture'],
    images: [
      {
        id: 'img-fashion-11-1',
        url: 'https://images.unsplash.com/photo-1584273143981-41c073dfe8f8?auto=format&fit=crop&w=800&q=80',
        altText: 'Tactile brushed black mohair cardigan texture detail with horn buttons',
      },
    ],
    options: [
      { name: 'Size', values: ['S', 'M', 'L'] },
      { name: 'Color', values: ['Onyx Black', 'Camel'] },
    ],
    variants: [
      {
        id: 'var-fashion-11-1',
        title: 'M / Onyx Black',
        sku: 'FAS-MHR-M-BLK',
        price: 290.0,
        options: { Size: 'M', Color: 'Onyx Black' },
        availableForSale: true,
        inventoryQuantity: 19,
      },
    ],
    rating: { average: 4.7, count: 22 },
    specifications: {
      Blend: '70% Kid Mohair, 30% Polyamide (Core strength)',
      Brushing: 'Natural Teasel Thistle Brushed',
    },
    featured: false,
    createdAt: '2026-01-28T08:00:00Z',
  },
  {
    id: 'prod-fashion-12',
    handle: 'cashmere-fringe-travel-wrap',
    title: 'Cashmere Fringe Travel Wrap',
    subtitle: 'Generous 200cm x 75cm gossamer cashmere shawl with raw eyelash fringe',
    description: 'An expansive cocoon of pure woven cashmere. Light enough to drape over bare shoulders in climate-controlled cabins, yet deeply insulating during brisk autumn walks.',
    price: 210.0,
    category: 'Knitwear',
    tags: ['knitwear', 'scarf', 'cashmere', 'travel'],
    images: [
      {
        id: 'img-fashion-12-1',
        url: 'https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?auto=format&fit=crop&w=800&q=80',
        altText: 'Model draped in generous charcoal grey cashmere travel wrap scarf',
      },
    ],
    options: [
      { name: 'Color', values: ['Charcoal Heather', 'Onyx Black', 'Camel'] },
    ],
    variants: [
      {
        id: 'var-fashion-12-1',
        title: 'Charcoal Heather',
        sku: 'FAS-WRP-CHR',
        price: 210.0,
        options: { Color: 'Charcoal Heather' },
        availableForSale: true,
        inventoryQuantity: 30,
      },
    ],
    rating: { average: 4.8, count: 19 },
    specifications: {
      Dimensions: '200cm length x 75cm width',
      Material: '100% Spun Cashmere',
    },
    featured: false,
    createdAt: '2026-01-30T08:00:00Z',
  },
  {
    id: 'prod-fashion-13',
    handle: 'chunky-lug-sole-derby-shoe',
    title: 'Chunky Lug-Sole Derby Shoe',
    subtitle: 'Goodyear welted box calf leather with exaggerated Vibram commando tread',
    description: 'Subverting the classic derby with brutalist proportions. Constructed from polished French box calfskin mounted onto an ultra-lightweight extruded Vibram lug outsole.',
    price: 360.0,
    compareAtPrice: 420.0,
    category: 'Footwear',
    tags: ['footwear', 'derby', 'leather', 'shoes', 'bestseller'],
    images: [
      {
        id: 'img-fashion-13-1',
        url: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=800&q=80',
        altText: 'Pair of polished black box calf chunky lug sole derby shoes',
      },
    ],
    options: [
      { name: 'Size', values: ['EU 40', 'EU 41', 'EU 42', 'EU 43', 'EU 44'] },
      { name: 'Color', values: ['Onyx Black'] },
    ],
    variants: [
      {
        id: 'var-fashion-13-1',
        title: 'EU 42 / Onyx Black',
        sku: 'FAS-DRB-42-BLK',
        price: 360.0,
        compareAtPrice: 420.0,
        options: { Size: 'EU 42', Color: 'Onyx Black' },
        availableForSale: true,
        inventoryQuantity: 12,
      },
      {
        id: 'var-fashion-13-2',
        title: 'EU 43 / Onyx Black',
        sku: 'FAS-DRB-43-BLK',
        price: 360.0,
        compareAtPrice: 420.0,
        options: { Size: 'EU 43', Color: 'Onyx Black' },
        availableForSale: true,
        inventoryQuantity: 10,
      },
    ],
    rating: { average: 4.9, count: 53 },
    specifications: {
      Upper: 'Full-Grain French Box Calfskin',
      Construction: '360° Goodyear Storm Welt',
      Sole: 'Custom Vibram Vi-Lite Lug Tread',
      Origin: 'Handcrafted in Northamptonshire, England',
    },
    featured: false,
    createdAt: '2026-02-01T08:00:00Z',
  },
  {
    id: 'prod-fashion-14',
    handle: 'brutalist-calfskin-chelsea-boot',
    title: 'Brutalist Calfskin Chelsea Boot',
    subtitle: 'Square-toe pull-on Chelsea with heavy stacked leather sole and tonal elastic',
    description: 'Sharply defined square chiselled toe and high-rise ankle shaft. Double-layer vegetable tanned leather midsole with concealed inner pull-tabs for sleek minimalist line.',
    price: 430.0,
    category: 'Footwear',
    tags: ['footwear', 'chelsea', 'boots', 'leather'],
    images: [
      {
        id: 'img-fashion-14-1',
        url: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=800&q=80',
        altText: 'Side angle of square-toe black calfskin chelsea boots with stacked heel',
      },
    ],
    options: [
      { name: 'Size', values: ['EU 41', 'EU 42', 'EU 43', 'EU 44'] },
    ],
    variants: [
      {
        id: 'var-fashion-14-1',
        title: 'EU 42',
        sku: 'FAS-CHL-42',
        price: 430.0,
        options: { Size: 'EU 42' },
        availableForSale: true,
        inventoryQuantity: 14,
      },
    ],
    rating: { average: 4.8, count: 37 },
    specifications: {
      Leather: 'Tuscan Vegetable-Tanned Calfskin',
      ToeProfile: 'Architectural Chisel Square Toe',
      HeelHeight: '38mm Stacked Leather Cuban Heel',
    },
    featured: false,
    createdAt: '2026-02-03T08:00:00Z',
  },
  {
    id: 'prod-fashion-15',
    handle: 'sculptural-leather-tote-bag',
    title: 'Sculptural Leather Tote Bag',
    subtitle: 'Seamless edge-painted calfskin structured tote with magnetic bridge closure',
    description: 'Folded architectural leather forms creating rigid symmetry. Features a micro-suede interior with a detachable zippered leather document pouch and 16-inch laptop pocket.',
    price: 450.0,
    compareAtPrice: 520.0,
    category: 'Footwear', // accessories/leather
    tags: ['footwear', 'bags', 'leather', 'accessories', 'luxury'],
    images: [
      {
        id: 'img-fashion-15-1',
        url: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=800&q=80',
        altText: 'Sculptural structured black leather tote bag resting on marble pedestal',
      },
    ],
    options: [
      { name: 'Color', values: ['Onyx Black', 'Bone White'] },
    ],
    variants: [
      {
        id: 'var-fashion-15-1',
        title: 'Onyx Black',
        sku: 'FAS-TOT-BLK',
        price: 450.0,
        compareAtPrice: 520.0,
        options: { Color: 'Onyx Black' },
        availableForSale: true,
        inventoryQuantity: 18,
      },
    ],
    rating: { average: 4.9, count: 41 },
    specifications: {
      Leather: 'Smooth Semi-Matte Italian Calfskin',
      Capacity: 'Fits 16-inch MacBook Pro',
      Dimensions: '42cm x 34cm x 14cm',
    },
    featured: false,
    createdAt: '2026-02-05T08:00:00Z',
  },
  {
    id: 'prod-fashion-16',
    handle: 'handcrafted-calfskin-minimalist-belt',
    title: 'Handcrafted Calfskin Minimalist Belt',
    subtitle: '30mm vegetable-tanned full grain belt with brushed palladium buckle',
    description: 'Precision bevelled and burnished edges dyed by hand. Fastened with a subtle cast brass buckle plated in brushed palladium with zero exterior branding.',
    price: 110.0,
    category: 'Footwear', // accessories
    tags: ['footwear', 'belt', 'leather', 'accessories'],
    images: [
      {
        id: 'img-fashion-16-1',
        url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
        altText: 'Rolled black calfskin dress belt showing brushed palladium metal buckle',
      },
    ],
    options: [
      { name: 'Size', values: ['85cm', '90cm', '95cm', '100cm'] },
    ],
    variants: [
      {
        id: 'var-fashion-16-1',
        title: '90cm',
        sku: 'FAS-BLT-90',
        price: 110.0,
        options: { Size: '90cm' },
        availableForSale: true,
        inventoryQuantity: 35,
      },
    ],
    rating: { average: 4.7, count: 28 },
    specifications: {
      Width: '30mm (1.18 inches)',
      Leather: 'English Bridle Vegetable Tanned Leather',
      Buckle: 'Solid Brass with Palladium Satin Finish',
    },
    featured: false,
    createdAt: '2026-02-07T08:00:00Z',
  },
];

export default fashionProducts;
